In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import math
from re import X

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [ ]:
# pip install fastparquet

# 데이터 열어보기

In [ ]:
plt.rcParams['font.family'] = 'AppleGothic'
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Parquet 데이터 불러오기

In [ ]:
registration = pd.read_parquet('registration.parquet')
change = pd.read_parquet('change.parquet')
cancel = pd.read_parquet('cancel.parquet')
new = pd.read_parquet('new.parquet')
transfer_1 = pd.read_parquet('transfer_1.parquet')
pledge = pd.read_parquet('pledge.parquet')

In [ ]:
registration.reset_index(inplace = True, drop = True)
change.reset_index(inplace = True, drop = True)
cancel.reset_index(inplace = True, drop = True)
new.reset_index(inplace = True, drop = True)
transfer_1.reset_index(inplace = True, drop = True)
pledge.reset_index(inplace = True, drop = True)

#신규등록정보 (2017.04 - 2022.07)

- 제원관리번호(manage_id) : 자동차 제작사 혹은 수입사가 관련 기관에 해당 모델에 관한 자세한 제원 정보를 주게 되면 각 모델 별 제원을 관리하는 제원관리 번호가 발급  
    - 제원 : 자동차 설계나 제조의 표준이 되고 형식승인을 받을 때 요구되는 항목  
- 차종명(vehicle_type) : 특수,화물로 구분  
- 차종유형(vehicle_model) : ['견인', '특수작업형', '구난', '일반형-픽업', '일반형-카고', '특수용도형-특수용도형', '밴', '특수용도형-피견인', '덤프', '특수용도형-탱크로리', '특수용도형']  
    - 견인/피견인 : 견인 가능한 차량 /불가차량  
    - 구난 : 견인차  
- 차종분류명(vehicle_cat) : 대/중/소/경/nan  
- 배기량(displacement) : 엔진 내부적으로 피스톤이 움직일 때 흡입, 배출되는 공기의 양  
    - 높으면 엔진의 크기가 크고 소비되는 연료도 많음 (일반적으로) 
- 승차정원수(passenger) : 앉을수 있는 승객 수
- 최대적재량(max_load) : 화물차 짐칸에 실을 수 있는 화물의 최대 분량  
- 차명(vehecle_name) : 차종 이름  
- 모델연도(model_year) : 모델 만들어진 연도
- 사용연료명(fuel) : 사용하는 연료명
- 국산수입구분명(dom_import) : ['국산', '외산']
- 차대차체형상명(vehicle_body) : 트럭형상  
    - 캡 오버 : 차량의 캡이 맨 앞 끝까지 위치한 형식  
    - 보넷 : 엔진이 위치한 보닛이 앞으로 튀어나온 형태 (컨벤셔널타입이라고도 부름)  
    - 세미보넷 : 엔진 룸의 반 정도가 전면으로 돌출된 차량  
- 차체길이(len) 
- 차체너비(width)
- 차체높이(height)
- 축간거리(wheelbase)
- 전윤간거리(front_wb)
- 후윤간거리(back_wb)
- 변속기종류명(transmission) : ['자동', '수동', '반자동', '변속기 없음', '기타', nan, '무단']  
- 차대번호(vin) : 차대번호는 차체 그 자체만의 고유번호  
- 등록관청명(reg_area) : 등록한 특별시/도 지역  
- 용도구분명(purpose) : 용도구분  
    - 관용 : 정부기관 혹은 기업체에서 업무용으로 사용되는 차량 
- 등록일(sale_reg_date) : 등록일자  
- 등록상세명(reg_detail) : ['일반소유용', '매매상품용'] 
- 최초등록일(first_reg_date) : 최초 등록날짜
- 제작년월일(man_date) : 제작 년/월/일
- 회원구분명(member_classi) : ['법인및사업자', '개인']
- 신청구분명(apply_category) : ['신조차 신규등록', '수입차 신규등록', '부활차이전등록', '부활차단순등록']  
- 취득금액(pur_amount) : 차량 구매한 금액 
- 원동기최고출력(max_output) : 마력  
- 연료소비율(consum_rate) : 연료 1리터로 주행할 수 있는 거리(킬로미터)  
- 차량총중량(weight)
- 최초제원관리번호(first_manage_id)
- 원동기RPM값(rpm) : 분당회전수 ( 엔진의 회전수가 높아질수록 토크가 일정하다면 출력도 높아진다. 그러나 동시에 연료 소모와 소음, 진동도 커진다. )  
- 구동방식코드(dri_system) : M X N 으로 표시하며 M 은 바퀴의 (위치)수, N 은 구동 바퀴의 (위치)수 로 표현  
    - 구동 바퀴 : 엔진에서 발생한 동력이 전달 되는 바퀴  
- 최초취득금액(first_pur_amount)

In [ ]:
new.head(1)

,제원관리번호,차종명,차종유형명,차종분류명,원동기형식명,형식명,배기량,승차정원수,최대적재량,차명,모델연도,사용연료명,국산수입구분명,차대차체형상명,차체길이,차체너비,차체높이,축간거리,전윤간거리,후윤간거리,변속기종류명,제원모델년도,차량등록번호,차대번호,등록관청명,용도구분명,신청구분명,등록일,등록상세명,최초등록일,제작년월일,회원구분명,회원등록번호,사용본거지주소명,소유자주소명,취득금액,원동기최고출력,연료소비율,차량중량,차량총중량,최초제원관리번호,원동기RPM값,타이어전전형식,타이어전후형식,타이어후전형식,타이어후중형식,타이어후후형식,구동방식코드,최초취득금액
0,BMY10004800004116,특수,구난,소형,672960,AMTK1.0ATP-UD5,2157.0,2,500.0,에이엠티언더리프트,2017,경유,국산,4륜구동 본넷트형,4960.0,1910.0,1790.0,3060.0,1570.0,1570.0,자동,2017.0,경기XX바XXXX,KPACA4AE1HXXXXXX,경기,영업용,신조차 신규등록,201704,일반소유용,201704,201703.0,법인및사업자,None,경기도 용인시 수지구,경기도 용인시 수지구,43000000.0,NaN,NaN,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN

In [ ]:
new.shape

(1353681, 49)

In [ ]:
new.columns

Index(['제원관리번호', '차종명', '차종유형명', '차종분류명', '원동기형식명', '형식명', '배기량', '승차정원수',
       '최대적재량', '차명', '모델연도', '사용연료명', '국산수입구분명', '차대차체형상명', '차체길이', '차체너비',
       '차체높이', '축간거리', '전윤간거리', '후윤간거리', '변속기종류명', '제원모델년도', '차량등록번호', '차대번호',
       '등록관청명', '용도구분명', '신청구분명', '등록일', '등록상세명', '최초등록일', '제작년월일', '회원구분명',
       '회원등록번호', '사용본거지주소명', '소유자주소명', '취득금액', '원동기최고출력', '연료소비율', '차량중량',
       '차량총중량', '최초제원관리번호', '원동기RPM값', '타이어전전형식', '타이어전후형식', '타이어후전형식',
       '타이어후중형식', '타이어후후형식', '구동방식코드', '최초취득금액'],
      dtype='object')

In [ ]:
set(new.columns.tolist()) - set(change.columns.tolist())

{'등록관청명', '신청구분명', '취득금액'}

In [ ]:
set(change.columns.tolist()) - set(new.columns.tolist())

{'구조변경명'}

##불필요 컬럼제거

In [ ]:
new.drop(['원동기형식명', '형식명', '사용본거지주소명','제원모델년도', '차대차체형상명', '소유자주소명', '회원등록번호', '차량등록번호','사용본거지주소명', '소유자주소명', '차량중량'],axis=1, inplace=True)
new.drop(['타이어전전형식', '타이어전후형식','타이어후전형식','타이어후중형식','타이어후후형식'],axis=1, inplace=True)

In [ ]:
## 컬럼명 영어로 변경

# '제원관리번호', '차종명', '차종유형명', '차종분류명', '배기량', '승차정원수', '최대적재량', '차명',
# '모델연도', '사용연료명', '국산수입구분명', '차대차체형상명', '차체길이', '차체너비', '차체높이', '축간거리',
# '전윤간거리', '후윤간거리', '변속기종류명', '차대번호', '등록관청명','용도구분명', '신청구분명','등록일', '등록상세명', '최초등록일',
# '제작년월일', '회원구분명', '취득금액', '원동기최고출력', '연료소비율', '차량총중량', '최초제원관리번호',
# '원동기RPM값', '구동방식코드', '최초취득금액'

new.columns = ['manage_id', 'vehicle_type', 'vehicle_model', 'vehicle_cat', 'displacement', 'passenger','max_load', 
                   'vehicle_name', 'model_year', 'fuel','dom_import', 'len', 'width', 'height', 'wheelbase',
                   'front_wb', 'back_wb', 'transmission', 'vin', 'reg_area', 'purpose', 'apply_category','sale_reg_date', 'reg_detail', 'first_reg_date','man_date', 
                   'member_classi', 'pur_amount', 'max_output', 'consum_rate', 'weight', 'first_manage_id', 'rpm', 'dri_system','first_pur_amount']

In [ ]:
new.drop(['wheelbase', 'front_wb', 'back_wb'], axis=1, inplace=True)

##제조사컬럼(mani) 생성 from 차대번호(vin)

In [ ]:
mani = []

for i in range(len(new)):
    if new.vin.iloc[i]:
        if new.vin.iloc[i][1] == 'V':
            mani.append('폭스바겐')
        elif new.vin.iloc[i][1] == 'A':
            mani.append('아우디')
        elif new.vin.iloc[i][1] == 'B':
          mani.append('BMW')
        elif new.vin.iloc[i][1] == 'D':
          mani.append('벤츠')
        elif new.vin.iloc[i][:2] == 'KP':
          mani.append('쌍용')
        elif new.vin.iloc[i][1] == 'M':
          mani.append('현대')
        elif new.vin.iloc[i][1] == 'L':
          mani.append('대우')
        elif new.vin.iloc[i][1] == 'N':
          mani.append('기아')
        elif new.vin.iloc[i][1] == 'P':
          mani.append('포르쉐')
        else:
          mani.append('기타')
    else:
        mani.append(None)

In [ ]:
new.vin.iloc[0][:2]

'KP'

In [ ]:
new['mani'] = mani
new.mani.value_counts(normalize= True)

현대      0.521715
기아      0.270414
쌍용      0.132305
대우      0.035611
기타      0.029093
폭스바겐    0.007283
아우디     0.001584
벤츠      0.001347
포르쉐     0.000384
BMW     0.000265
Name: mani, dtype: float64

In [ ]:
# sale_reg_date
new['sale_reg_date'] = new['sale_reg_date'].astype({'sale_reg_date':'object'})

for i, value in enumerate(new['sale_reg_date'].values):
    new['sale_reg_date'].values[i] = f"{str(value)[:4]}-{str(value)[4:]}-01"

In [ ]:
# first_reg_date 
new['first_reg_date'] = new['first_reg_date'].astype({'first_reg_date':'object'})

for i, value in enumerate(new['first_reg_date'].values):
    new['first_reg_date'].values[i] = f"{str(value)[:4]}-{str(value)[4:]}-01"

In [ ]:
# man_date
new.dropna(subset=['man_date'], axis=0, inplace=True)
new['man_date'] = new['man_date'].astype({'man_date':'int64'})
new['man_date'] = new['man_date'].astype({'man_date':'object'})

for i, value in enumerate(new['man_date'].values):
    new['man_date'].values[i] = f"{str(value)[:4]}-{str(value)[4:]}-01"

In [ ]:
# 모델연도 datetime형태로 변경
new['sale_reg_date'] = pd.to_datetime(new['sale_reg_date'],format='%Y-%m-%d')
new['first_reg_date'] = pd.to_datetime(new['first_reg_date'],format='%Y-%m-%d')
new['man_date'] = pd.to_datetime(new['man_date'],format='%Y-%m-%d')

In [ ]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1353673 entries, 0 to 1353680
Data columns (total 36 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   manage_id         1353673 non-null  object
 1   vehicle_type      1353673 non-null  object
 2   vehicle_model     1353673 non-null  object
 3   vehicle_cat       1353673 non-null  object
 4   displacement      1353638 non-null  float32
 5   passenger         1353673 non-null  int32
 6   max_load          1353589 non-null  float32
 7   vehicle_name      1353673 non-null  object
 8   model_year        1353673 non-null  int32
 9   fuel              1297220 non-null  object
 10  dom_import        1353673 non-null  object
 11  len               1353662 non-null  float32
 12  width             1353662 non-null  float32
 13  height            1353662 non-null  float32
 14  wheelbase         1353577 non-null  float32
 15  front_wb          1352262 non-null  float32
 16  back_wb           1353576 non-null  float32
 17  transmission      1353641 non-null  object
 18  vin               1353664 non-null  object
 19  reg_area          1353673 non-null  object
 20  purpose           1353673 non-null  object
 21  apply_category    1353673 non-null  object
 22  sale_reg_date     1353673 non-null  datetime64[ns]
 23  reg_detail        1353673 non-null  object
 24  first_reg_date    1353673 non-null  datetime64[ns]
 25  man_date          1353673 non-null  datetime64[ns]
 26  member_classi     1353673 non-null  object
 27  pur_amount        1353668 non-null  float64
 28  max_output        596304 non-null   float32
 29  consum_rate       599237 non-null   float32
 30  weight            623818 non-null   float32
 31  first_manage_id   587996 non-null   object
 32  rpm               595951 non-null   float32
 33  dri_system        610084 non-null   object
 34  first_pur_amount  648632 non-null   float32
 35  mani              1353664 non-null  object
dtypes: datetime64[ns](3), float32(13), float64(1), int32(2), object(17)
memory usage: 304.7+ MB

## 결측치 처리

###제작년월일(man_date) 결측치

In [ ]:
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement            35
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                     11
width                   11
height                  11
wheelbase               96
front_wb              1411
back_wb                 97
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757369
consum_rate         754436
weight              729855
first_manage_id     765677
rpm                 757722
dri_system          743589
first_pur_amount    705041
mani                     9
dtype: int64

In [ ]:
new['man_date'].isnull().sum()

8

In [ ]:
#man_date na 8개 drop
new.dropna(subset=['man_date'], axis=0, inplace=True)

In [ ]:
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement            35
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                     11
width                   11
height                  11
wheelbase               96
front_wb              1411
back_wb                 97
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757369
consum_rate         754436
weight              729855
first_manage_id     765677
rpm                 757722
dri_system          743589
first_pur_amount    705041
mani                     9
dtype: int64

In [ ]:
new[new['vin'].isnull()]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehecle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
110880,10173900000000,화물,특수용도형-특수용도형,대형,7545.0,5,3000.0,우리소방펌프자동차,2001,경유,국산,캡오버형,7630.0,2240.0,2800.0,4260.0,1770.0,1660.0,수동,None,인천,자가용,부활차이전등록,2017-09-01,일반소유용,2001-03-01,2001-03-01,개인,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN
113496,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,피견인형,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,자가용,부활차단순등록,2017-09-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN
126374,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,피견인형,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,자가용,부활차단순등록,2017-09-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN
156334,10206700000000,화물,특수용도형-특수용도형,중형,2957.0,3,1000.0,대동봉고프런티어 킹캡윙바디,2002,경유,국산,"ㅁ형프레임,캡오버형",5105.0,1800.0,2550.0,2585.0,1490.0,1350.0,수동,None,대구,자가용,부활차단순등록,2017-11-01,일반소유용,2002-11-01,2002-11-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN
209411,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,피견인형,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,영업용,부활차이전등록,2018-02-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN
211792,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,피견인형,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,영업용,부활차이전등록,2018-02-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN
510033,10122600000000,화물,특수용도형-특수용도형,중형,3581.0,3,2000.0,한성2000L다목적방제차,2000,경유,국산,"H형,캡오버형",5230.0,1965.0,2690.0,2760.0,1470.0,1490.0,수동,None,광주,자가용,부활차단순등록,2019-03-01,일반소유용,2000-09-01,2000-09-01,개인,2800000.0,NaN,NaN,NaN,None,NaN,None,NaN
779548,10165100000000,화물,특수용도형-특수용도형,대형,0.0,0,27500.0,미래40피트구즈넥콘테이너샤시,2002,None,국산,피견인형,12480.0,2440.0,1530.0,10500.0,0.0,1820.0,기타,None,경기,자가용,부활차단순등록,2020-04-01,일반소유용,2003-02-01,2002-12-01,법인및사업자,0.0,NaN,0.0,30950.0,None,NaN,None,0.0
1134890,20098100000000,화물,특수용도형-특수용도형,중형,5958.0,3,2500.0,유니목1200,2001,경유,외산,본네트형,4470.0,2110.0,2620.0,2650.0,1660.0,1680.0,수동,None,경남,자가용,부활차이전등록,2021-08-01,일반소유용,1991-08-01,1991-08-01,개인,0.0,126.0,8.2,7285.0,None,2400.0,None,0.0

In [ ]:
new[new.displacement.isnull()].head()

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
20595,B0710019600013311,화물,특수용도형-피견인,대형,NaN,0,27000.0,두성 40피트 구즈넥 콘테이너샤시,2012,None,국산,12550.0,2490.0,1620.0,9100.0,0.0,1840.0,변속기 없음,KN9DNEZTZCXXXXXX,경북,영업용,부활차단순등록,2017-04-01,일반소유용,2012-01-01,2011-12-01,법인및사업자,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
95744,B0810002800003304,화물,특수용도형-특수용도형,대형,NaN,0,27000.0,한특40피트구즈넥샤시,2004,None,국산,12565.0,2470.0,1660.0,10480.0,0.0,1850.0,기타,KN9DNEXTZ4XXXXXX,부산,영업용,부활차이전등록,2017-08-01,일반소유용,2004-06-01,2004-06-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
126373,B1610001800003303,화물,특수용도형-특수용도형,대형,NaN,0,26900.0,한원40A구즈넥트레일러,2004,None,국산,12520.0,2480.0,1640.0,10430.0,0.0,1820.0,기타,KN9DNEXTZ4XXXXXX,인천,영업용,부활차이전등록,2017-09-01,일반소유용,2004-09-01,2004-08-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
161398,B1P10005000003311,화물,특수용도형-피견인,대형,NaN,0,24400.0,알텍 3-PTC 트레일러,2011,None,국산,12470.0,2490.0,1390.0,10050.0,0.0,1850.0,변속기 없음,KN9CNEZTZBXXXXXX,경기,영업용,부활차이전등록,2017-11-01,일반소유용,2012-02-01,2012-01-01,법인및사업자,5000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
202924,B0G10010600003310,화물,특수용도형-특수용도형,대형,NaN,0,25000.0,대흥저상트레일러,2010,None,국산,10250.0,2750.0,1690.0,9065.0,0.0,2060.0,기타,KN9ENEZTZAXXXXXX,충남,자가용,부활차단순등록,2018-01-01,일반소유용,2010-03-01,2010-03-01,개인,34000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아

In [ ]:
new[new['first_pur_amount'] == 0].shape

(491, 36)

In [ ]:
new[new['pur_amount'] == 0].shape
# 과거 데이터(2017~2019)에 1500개 0이 더있다.
# 둘다 살리기로~

(2105, 36)

In [ ]:
new.first_pur_amount.tail(7)

1353674    25300000.0
1353675    39900000.0
1353676    39900000.0
1353677    40000000.0
1353678    40000000.0
1353679    26600000.0
1353680    22100000.0
Name: first_pur_amount, dtype: float32

In [ ]:
new.first_pur_amount.tail(7)

1353674    25300000.0
1353675    39900000.0
1353676    39900000.0
1353677    40000000.0
1353678    40000000.0
1353679    26600000.0
1353680    22100000.0
Name: first_pur_amount, dtype: float32

In [ ]:
new[new['pur_amount'] == 0].shape

(2105, 36)

In [ ]:
new.vin[:10]

#KPACA4AE1HXXXXXX
#K-제조국
#P-제조사
#A-차량구분
#CA4AE - 차량특성(차종, 배기량 등)
#1 - 보안코드
#H - ...

index
0    KPACA4AE1HXXXXXX
1    KNCWJZ76AHXXXXXX
2    KMFHA17GPHXXXXXX
3    KNCSJZ76AHXXXXXX
4    KNCSJZ76AHXXXXXX
5    KNCSJZ76AHXXXXXX
6    KNCWJZ76AHXXXXXX
7    KNCSJZ76AHXXXXXX
8    KMFHA17GPHXXXXXX
9    KMFHA17GPHXXXXXX
Name: vin, dtype: object

###배기량(displacement)  결측치

In [ ]:
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement            35
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                     11
width                   11
height                  11
wheelbase               96
front_wb              1411
back_wb                 97
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757369
consum_rate         754436
weight              729855
first_manage_id     765677
rpm                 757722
dri_system          743589
first_pur_amount    705041
mani                     9
dtype: int64

In [ ]:
# 확인시 대부분 트레일러, 콘테이너샤시
new[new['displacement'].isnull()].head()

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
20595,B0710019600013311,화물,특수용도형-피견인,대형,NaN,0,27000.0,두성 40피트 구즈넥 콘테이너샤시,2012,None,국산,12550.0,2490.0,1620.0,9100.0,0.0,1840.0,변속기 없음,KN9DNEZTZCXXXXXX,경북,영업용,부활차단순등록,2017-04-01,일반소유용,2012-01-01,2011-12-01,법인및사업자,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
95744,B0810002800003304,화물,특수용도형-특수용도형,대형,NaN,0,27000.0,한특40피트구즈넥샤시,2004,None,국산,12565.0,2470.0,1660.0,10480.0,0.0,1850.0,기타,KN9DNEXTZ4XXXXXX,부산,영업용,부활차이전등록,2017-08-01,일반소유용,2004-06-01,2004-06-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
126373,B1610001800003303,화물,특수용도형-특수용도형,대형,NaN,0,26900.0,한원40A구즈넥트레일러,2004,None,국산,12520.0,2480.0,1640.0,10430.0,0.0,1820.0,기타,KN9DNEXTZ4XXXXXX,인천,영업용,부활차이전등록,2017-09-01,일반소유용,2004-09-01,2004-08-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
161398,B1P10005000003311,화물,특수용도형-피견인,대형,NaN,0,24400.0,알텍 3-PTC 트레일러,2011,None,국산,12470.0,2490.0,1390.0,10050.0,0.0,1850.0,변속기 없음,KN9CNEZTZBXXXXXX,경기,영업용,부활차이전등록,2017-11-01,일반소유용,2012-02-01,2012-01-01,법인및사업자,5000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
202924,B0G10010600003310,화물,특수용도형-특수용도형,대형,NaN,0,25000.0,대흥저상트레일러,2010,None,국산,10250.0,2750.0,1690.0,9065.0,0.0,2060.0,기타,KN9ENEZTZAXXXXXX,충남,자가용,부활차단순등록,2018-01-01,일반소유용,2010-03-01,2010-03-01,개인,34000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아

In [ ]:
# new.groupby(['vehicle_cat']).displacement.median()

vehicle_cat
경형     796.0
대형    6728.0
소형    2497.0
중형    3800.0
Name: displacement, dtype: float32

In [ ]:
new.reset_index(inplace = True, drop = True)

In [ ]:
for i in range(len(new)):
    if math.isnan(new.loc[i, 'displacement']):
          new.loc[i, 'displacement'] = 0

In [ ]:
# median 구할시 코드
# for i in range(len(new)):
#     if (new.loc[i, 'vehicle_cat'] == '경형') & math.isnan(new.loc[i, 'displacement']):
#           new.loc[i, 'displacement'] = 796.0
#     elif (new.loc[i, 'vehicle_cat'] == '대형') & math.isnan(new.loc[i, 'displacement']):
#           new.loc[i, 'displacement']= 6728.0
#     elif (new.loc[i, 'vehicle_cat'] == '소형') & math.isnan(new.loc[i, 'displacement']):
#           new.loc[i, 'displacement']= 2497.0
#     elif (new.loc[i, 'vehicle_cat'] == '중형') & math.isnan(new.loc[i, 'displacement']):
#           new.loc[i, 'displacement']= 3800.0

In [ ]:
len(new[new['displacement'] == 0])

56517

###최대적재량(max_load) 결측치

In [ ]:
# 적재가 안되는 사다리차등이다.
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                     11
width                   11
height                  11
wheelbase               96
front_wb              1411
back_wb                 97
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757369
consum_rate         754436
weight              729855
first_manage_id     765677
rpm                 757722
dri_system          743589
first_pur_amount    705041
mani                     9
dtype: int64

In [ ]:
new[new.max_load.isna()]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
439,B9P10002700014112,특수,특수작업형,소형,2497.0,2,NaN,드림 사다리차,2013,경유,국산,5285.0,1740.0,2950.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ADXXXXXX,충남,자가용,부활차단순등록,2017-04-01,일반소유용,2013-07-01,2012-12-01,개인,51000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
525,BAE10002700014115,특수,특수작업형,소형,2497.0,2,NaN,천하사다리차2,2016,경유,국산,5255.0,1750.0,2650.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AGXXXXXX,충북,자가용,부활차단순등록,2017-04-01,일반소유용,2015-11-01,2015-11-01,개인,50000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
22915,BAH10001200004113,특수,특수작업형,소형,2497.0,2,NaN,한길18M고소작업차,2013,경유,국산,5435.0,1840.0,2660.0,2615.0,1490.0,1340.0,수동,KNCSJX76ADXXXXXX,충북,자가용,부활차이전등록,2017-05-01,일반소유용,2013-08-01,2013-07-01,개인,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
69613,B7J10003900014314,특수,특수작업형,대형,5890.0,2,NaN,한신울트라고소작업차,2015,경유,국산,9590.0,2495.0,3925.0,4900.0,2075.0,1760.0,수동,KLTCC4ATDFXXXXXX,강원,자가용,부활차단순등록,2017-07-01,일반소유용,2015-03-01,2014-10-01,개인,102000000.0,NaN,NaN,NaN,None,NaN,None,NaN,대우
109446,BYV10000800024216,특수,특수작업형,중형,2497.0,3,NaN,하나중공업고소작업차,2017,경유,국산,5625.0,1920.0,2540.0,2740.0,1475.0,1435.0,수동,KMFVA17RPHXXXXXX,강원,자가용,부활차단순등록,2017-09-01,일반소유용,2016-10-01,2016-09-01,개인,50000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
109642,B3510004400004110,특수,특수작업형,소형,2902.0,3,NaN,동해고소작업차-1011,2011,경유,국산,5440.0,1760.0,2770.0,2810.0,1470.0,1270.0,수동,KNCWJZ74ABXXXXXX,경기,자가용,부활차이전등록,2017-09-01,일반소유용,2011-02-01,2011-01-01,법인및사업자,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
109811,B7J10003100004312,특수,특수작업형,대형,5899.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,8370.0,2325.0,3780.0,4260.0,1870.0,1800.0,수동,KMFLA18KPDXXXXXX,제주,자가용,부활차이전등록,2017-09-01,일반소유용,2013-05-01,2013-04-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
131356,BT810000300034115,특수,특수작업형,소형,2497.0,3,NaN,아톰고소작업차,2015,경유,국산,5510.0,1890.0,2530.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AFXXXXXX,경기,자가용,부활차단순등록,2017-10-01,일반소유용,2015-08-01,2015-07-01,법인및사업자,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
131421,B7J10002800004311,특수,특수작업형,대형,5890.0,2,NaN,한신 울트라 고소 작업차,2012,경유,국산,9670.0,2495.0,3920.0,4900.0,2090.0,1760.0,수동,KLTCC4AT1CXXXXXX,강원,자가용,부활차이전등록,2017-10-01,일반소유용,2011-08-01,2011-07-01,개인,5000000.0,NaN,NaN,NaN,None,NaN,None,NaN,대우
131448,BT810000300024114,특수,특수작업형,소형,2497.0,3,NaN,아톰고소작업차,2014,경유,국산,5510.0,1890.0,2530.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AEXXXXXX,경기,자가용,부활차단순등록,2017-10-01,일반소유용,2014-07-01,2014-07-01,법인및사업자,40000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
148252,B4S10009700014112,특수,특수작업형,소형,2497.0,2,NaN,호룡 엘리카 고가사다리차,2013,경유,국산,5545.0,1750.0,2790.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ADXXXXXX,경기,자가용,부활차이전등록,2017-11-01,일반소유용,2013-03-01,2012-12-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
207645,B3510014900004214,특수,특수작업형,중형,3933.0,3,NaN,동해절연고소작업차,2014,경유,국산,5630.0,2100.0,3680.0,2820.0,1665.0,1495.0,수동,KMFGA17HPEXXXXXX,충남,자가용,부활차단순등록,2018-02-01,일반소유용,2015-01-01,2015-01-01,법인및사업자,77000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
207657,B3510014900004214,특수,특수작업형,중형,3933.0,3,NaN,동해절연고소작업차,2014,경유,국산,5630.0,2100.0,3680.0,2820.0,1665.0,1495.0,수동,KMFGA17HPEXXXXXX,충남,자가용,부활차단순등록,2018-02-01,일반소유용,2015-01-01,2015-01-01,법인및사업자,77000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
249233,B5E10001600004210,특수,특수작업형,중형,3933.0,3,NaN,노바스 스카이점보 고소작업차,2011,경유,국산,5825.0,2000.0,3170.0,2820.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경기,자가용,부활차이전등록,2018-04-01,매매상품용,2011-05-01,2011-05-01,개인,12000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
296348,B7J10002800024313,특수,특수작업형,대형,5890.0,2,NaN,한신 울트라 고소 작업차,2014,경유,국산,9670.0,2495.0,3920.0,4900.0,2090.0,1760.0,수동,KLTCC4ATDEKXXXXXX,강원,영업용,부활차이전등록,2018-06-01,일반소유용,2013-07-01,2013-07-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,대우
296596,B9P10002700014112,특수,특수작업형,소형,2497.0,2,NaN,드림 사다리차,2013,경유,국산,5285.0,1740.0,2950.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ADKXXXXXX,경기,자가용,부활차단순등록,2018-06-01,일반소유용,2013-06-01,2012-12-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
319138,B7Y10002400014211,특수,특수작업형,중형,3933.0,3,NaN,다산고소작업차,2012,경유,국산,5770.0,2010.0,3025.0,2820.0,1665.0,1495.0,수동,KMFGA17HPCCXXXXXX,경북,자가용,부활차단순등록,2018-07-01,일반소유용,2013-03-01,2013-03-01,개인,114000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
343711,B3510016000004215,특수,특수작업형,중형,3933.0,3,NaN,동해절연고소작업차,2015,경유,국산,5770.0,2100.0,3625.0,2850.0,1680.0,1495.0,수동,KMFHA17GPFCXXXXXX,경남,자가용,부활차이전등록,2018-08-01,일반소유용,2016-03-01,2016-03-01,개인,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
361202,BPR10000200004112,특수,특수작업형,소형,2497.0,2,NaN,진보고소작업차,2012,경유,국산,5550.0,1750.0,2600.0,2615.0,1490.0,1340.0,수동,KNCSJX76ACKXXXXXX,서울,자가용,부활차이전등록,2018-09-01,일반소유용,2012-07-01,2012-06-01,법인및사업자,6000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
361352,BAE10002300004214,특수,특수작업형,중형,3933.0,3,NaN,천하사다리차,2014,경유,국산,7580.0,2165.0,3260.0,3775.0,1665.0,1495.0,수동,KMFGA17HPECXXXXXX,충북,자가용,부활차이전등록,2018-09-01,일반소유용,2014-08-01,2014-07-01,개인,20000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
380272,B9P10002100014211,특수,특수작업형,중형,3933.0,3,NaN,드림사다리차,2012,경유,국산,6270.0,1900.0,3060.0,2740.0,1475.0,1435.0,수동,KMFVA17HPCCXXXXXX,경기,자가용,부활차단순등록,2018-10-01,일반소유용,2012-07-01,2012-07-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
427355,B4S10008100004210,특수,특수작업형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2011,경유,국산,7395.0,2100.0,3320.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경기,자가용,부활차이전등록,2018-12-01,매매상품용,2011-07-01,2011-06-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
427573,B7Y10003700004114,특수,특수작업형,소형,2497.0,2,NaN,다산고소작업차,2014,경유,국산,5785.0,1755.0,2560.0,2810.0,1470.0,1270.0,수동,KNCWJZ76AEKXXXXXX,경기,자가용,부활차단순등록,2018-12-01,일반소유용,2014-07-01,2014-07-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
473687,B4S10009100014211,특수,특수작업형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2012,경유,국산,7315.0,2100.0,3010.0,3775.0,1665.0,1495.0,수동,KMFGA17HPCCXXXXXX,제주,자가용,부활차이전등록,2019-02-01,일반소유용,2012-06-01,2012-06-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
473753,BCB10001100004210,특수,특수작업형,중형,3933.0,3,NaN,JW280W 고소작업차,2011,경유,국산,5795.0,2060.0,2990.0,2820.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,서울,자가용,부활차이전등록,2019-02-01,일반소유용,2011-06-01,2011-06-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
473833,B7J10004300014315,특수,특수작업형,대형,6299.0,3,NaN,한신고소작업차,2016,경유,국산,7680.0,2320.0,3495.0,3845.0,1870.0,1660.0,수동,KMFLA18TPGCXXXXXX,제주,자가용,부활차이전등록,2019-02-01,일반소유용,2016-07-01,2016-04-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
473886,B7J10003200014212,특수,특수작업형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,7385.0,2130.0,2895.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,경북,자가용,부활차이전등록,2019-02-01,일반소유용,2013-08-01,2013-08-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
474080,B7J10004900004216,특수,특수작업형,중형,2497.0,3,NaN,한신울트라고소작업차,2016,경유,국산,5595.0,1900.0,2380.0,2740.0,1475.0,1435.0,수동,KMFVA17RPGCXXXXXX,제주,자가용,부활차단순등록,2019-02-01,일반소유용,2016-06-01,2016-05-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
491978,B4S10008800004111,특수,특수작업형,소형,2902.0,3,NaN,호룡 엘리카 고가사다리차,2011,경유,국산,5275.0,1740.0,2950.0,2615.0,1490.0,1340.0,수동,KNCSJZ74ABKXXXXXX,전남,영업용,부활차이전등록,2019-03-01,일반소유용,2011-07-01,2011-07-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
516412,B5E10001600004210,특수,특수작업형,중형,3933.0,3,NaN,노바스 스카이점보 고소작업차,2011,경유,국산,5825.0,2000.0,3170.0,2820.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경기,자가용,부활차이전등록,2019-04-01,매매상품용,2011-06-01,2011-06-01,개인,23500000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
516441,B3510004700024213,특수,특수작업형,중형,3933.0,3,NaN,동해고소작업차-1015,2013,경유,국산,6815.0,2180.0,3300.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,광주,자가용,부활차단순등록,2019-04-01,일반소유용,2013-03-01,2013-03-01,개인,24200000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
516463,B4S10008300014311,특수,특수작업형,대형,5890.0,2,NaN,호룡스카이 450SF고소작업차,2012,경유,국산,9680.0,2495.0,3890.0,4900.0,2075.0,1760.0,수동,KLTCC4AT1CKXXXXXX,강원,자가용,부활차단순등록,2019-04-01,일반소유용,2011-09-01,2011-09-01,개인,50000000.0,NaN,NaN,NaN,None,NaN,None,NaN,대우
541612,B4S10010100014312,특수,특수작업형,대형,5890.0,2,NaN,호룡스카이 4504N고소작업차,2013,경유,국산,9665.0,2495.0,3885.0,4900.0,2075.0,1760.0,수동,KLTCC4ATDDKXXXXXX,광주,자가용,부활차이전등록,2019-05-01,일반소유용,2013-04-01,2013-03-01,개인,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,대우
541783,B7Y10005400004216,특수,특수작업형,중형,3933.0,2,NaN,다산고소작업차,2017,경유,국산,5875.0,2000.0,2970.0,2850.0,1680.0,1495.0,수동,KMFHA17GPHCXXXXXX,대구,자가용,부활차단순등록,2019-05-01,일반소유용,2017-08-01,2017-07-01,개인,7000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
541796,B7Y10003200004113,특수,특수작업형,소형,2497.0,2,NaN,다산고소작업차,2013,경유,국산,5520.0,1760.0,2500.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ADKXXXXXX,경기,자가용,부활차단순등록,2019-05-01,일반소유용,2013-10-01,2013-10-01,개인,5000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
564289,B3510007300004112,특수,특수작업형,소형,2497.0,3,NaN,동해고소작업차-1202,2012,경유,국산,5365.0,1740.0,2560.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ACKXXXXXX,전남,자가용,부활차단순등록,2019-06-01,일반소유용,2012-05-01,2012-05-01,개인,37000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
564392,BAE10002300004214,특수,특수작업형,중형,3933.0,3,NaN,천하사다리차,2014,경유,국산,7580.0,2165.0,3260.0,3775.0,1665.0,1495.0,수동,KMFGA17HPECXXXXXX,대전,자가용,부활차단순등록,2019-06-01,일반소유용,2014-12-01,2014-11-01,개인,90900000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
585152,B9P10003100014114,특수,특수작업형,소형,2497.0,2,NaN,드림사다리차,2014,경유,국산,5165.0,1740.0,2580.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AEKXXXXXX,대구,자가용,부활차단순등록,2019-07-01,일반소유용,2014-04-01,2014-04-01,개인,48100000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
585222,BT810000300004112,특수,특수작업형,소형,2497.0,3,NaN,아톰고소작업차,2012,경유,국산,5510.0,1890.0,2530.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ACKXXXXXX,강원,자가용,부활차이전등록,2019-07-01,일반소유용,2012-09-01,2012-09-01,개인,2000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
585727,B4S10008200004210,특수,특수작업형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2011,경유,국산,7315.0,2100.0,2960.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경기,자가용,부활차이전등록,2019-07-01,일반소유용,2011-04-01,2011-03-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
585802,BCB10001300014211,특수,특수작업형,중형,3933.0,3,NaN,JW280M고소작업차,2012,경유,국산,7395.0,2105.0,2950.0,3775.0,1665.0,1495.0,수동,KMFGA17HPCCXXXXXX,경기,자가용,부활차단순등록,2019-07-01,일반소유용,2012-03-01,2012-02-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
643534,B9P10002500014111,특수,특수작업형,소형,2902.0,2,NaN,드림 사다리차,2012,경유,국산,5325.0,1740.0,2850.0,2615.0,1490.0,1340.0,수동,KNCSJZ74ACKXXXXXX,경기,자가용,부활차이전등록,2019-10-01,일반소유용,2012-03-01,2012-03-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
643639,B3510029800004118,특수,특수작업형,소형,2497.0,3,NaN,동해고소작업차,2019,경유,국산,5320.0,1740.0,2570.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AKKXXXXXX,경기,자가용,부활차단순등록,2019-10-01,일반소유용,2019-08-01,2019-08-01,개인,38500000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
663176,BAE10003300014216,특수,특수작업형,중형,2497.0,3,NaN,천하사다리차,2017,경유,국산,6230.0,1960.0,3120.0,2740.0,1475.0,1435.0,수동,KMFVA17RPHCXXXXXX,전북,자가용,부활차이전등록,2019-11-01,매매상품용,2017-02-01,2017-01-01,개인,42600000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
686116,B7J10003200014212,특수,특수작업형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,7385.0,2130.0,2895.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,경기,자가용,부활차이전등록,2019-12-01,일반소유용,2013-06-01,2013-04-01,법인및사업자,31300000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
686125,B3510027200004217,특수,특수작업형,중형,3933.0,3,NaN,동해절연고소작업차,2017,경유,국산,5810.0,2090.0,3640.0,2850.0,1680.0,1495.0,수동,KMFHA17GPHCXXXXXX,경남,자가용,부활차단순등록,2019-12-01,일반소유용,2017-10-01,2017-10-01,개인,148800000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
686366,B7Y10003100004112,특수,특수작업형,소형,2497.0,2,NaN,다산고소작업차,2012,경유,국산,5490.0,1760.0,2500.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ACKXXXXXX,경기,자가용,부활차단순등록,2019-12-01,일반소유용,2012-10-01,2012-10-01,개인,15300000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
686367,BAE10002600014115,특수,특수작업형,소형,2497.0,2,NaN,천하사다리차1,2016,경유,국산,5185.0,1750.0,2910.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AGKXXXXXX,경기,자가용,부활차단순등록,2019-12-01,일반소유용,2015-12-01,2015-11-01,개인,49000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아
719410,B4S10008100004210,특수,특수작업형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2011,경유,국산,7395.0,2100.0,3320.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,광주,영업용,부활차이전등록,2020-01-01,일반소유용,2011-07-01,2011-07-01,개인,26000000.0,160.0,10.0,7985.0,A0810005009663210,2500.0,None,110000000.0,현대
719432,B7J10002500004210,특수,특수작업형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2011,경유,국산,7395.0,2160.0,3135.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경기,자가용,부활차단순등록,2020-01-01,일반소유용,2011-04-01,2011-03-01,개인,10000000.0,160.0,10.0,8175.0,A0810005009663210,2500.0,None,105200000.0,현대
738370,B3510019500014216,특수,특수용도형,중형,3933.0,2,NaN,동해절연고소작업차,2017,경유,국산,5910.0,2090.0,3620.0,2850.0,1680.0,1495.0,수동,KMFHA17GPHCXXXXXX,전북,자가용,부활차단순등록,2020-02-01,일반소유용,2016-12-01,2016-11-01,개인,175000000.0,170.0,10.6,7895.0,A0810010101873215,2500.0,None,175000000.0,현대
758870,BAE10002700004115,특수,특수용도형,소형,2497.0,2,NaN,천하사다리차2,2015,경유,국산,5255.0,1750.0,2650.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AFKXXXXXX,대구,자가용,부활차단순등록,2020-03-01,일반소유용,2015-04-01,2015-03-01,개인,51800000.0,133.0,10.0,3490.0,A0110003127053114,3800.0,None,51800000.0,기아
780087,BVY10001500014216,특수,특수용도형,중형,3933.0,2,NaN,노바스스카이고소작업차,2017,경유,국산,7485.0,2120.0,2915.0,3850.0,1680.0,1495.0,수동,KMFHA17GPHCXXXXXX,경기,자가용,부활차이전등록,2020-04-01,일반소유용,2017-05-01,2017-04-01,개인,0.0,170.0,10.4,8090.0,A0810010100573215,2500.0,None,109000000.0,현대
800290,BT810002000004217,특수,특수용도형,중형,3933.0,3,NaN,지톤고소작업차,2017,경유,국산,5875.0,2090.0,3015.0,2850.0,1680.0,1495.0,수동,KMFHA17GPHCXXXXXX,제주,자가용,부활차이전등록,2020-05-01,일반소유용,2017-02-01,2017-02-01,개인,0.0,170.0,10.6,8115.0,A0810010102893216,2500.0,None,109000000.0,현대
847408,B4S10008800014111,특수,특수용도형,소형,2902.0,3,NaN,호룡 엘리카 고가사다리차,2012,경유,국산,5275.0,1740.0,2950.0,2615.0,1490.0,1340.0,수동,KNCSJZ74ACKXXXXXX,경기,자가용,부활차이전등록,2020-07-01,일반소유용,2011-11-01,2011-11-01,개인,0.0,126.0,11.2,3475.0,A0110003118463110,3800.0,None,35500000.0,기아
867323,BAE10002100004114,특수,특수용도형,소형,2497.0,2,NaN,천하 사다리차,2014,경유,국산,5170.0,1750.0,2900.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AEKXXXXXX,경기,영업용,부활차이전등록,2020-08-01,일반소유용,2014-05-01,2014-05-01,법인및사업자,0.0,133.0,10.0,3490.0,A0110003124693113,3800.0,None,50900000.0,기아
867509,B4S10011600004213,특수,특수용도형,중형,3933.0,3,NaN,호룡엘리카고가사다리차,2014,경유,국산,7730.0,2050.0,3230.0,3775.0,1665.0,1495.0,수동,KMFGA17HPECXXXXXX,경기,영업용,부활차이전등록,2020-08-01,일반소유용,2014-08-01,2014-07-01,법인및사업자,0.0,170.0,10.0,7675.0,A0810005012503213,2500.0,None,90900000.0,현대
889328,CCT10001000004120,특수,특수용도형,소형,2497.0,5,NaN,예스알브이캠핑카,2020,경유,국산,6490.0,2150.0,2830.0,3190.0,1485.0,1320.0,자동,KMFZCX7KBLUXXXXXX,대구,자가용,부활차이전등록,2020-09-01,일반소유용,2020-06-01,2020-06-01,개인,61500000.0,133.0,9.0,3495.0,B6610277500003119,3600.0,4x2,61300000.0,현대
912773,BCB10001700014212,특수,특수용도형,중형,3933.0,1,NaN,JW320 고소작업차,2013,경유,국산,7405.0,2120.0,2990.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,대구,자가용,부활차이전등록,2020-10-01,매매상품용,2013-06-01,2013-06-01,개인,10000000.0,160.0,10.0,8175.0,A0810005010433211,2500.0,None,103600000.0,현대
936348,B9P10002700004112,특수,특수용도형,소형,2497.0,2,NaN,드림 사다리차,2012,경유,국산,5285.0,1740.0,2950.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ACKXXXXXX,경기,자가용,부활차이전등록,2020-11-01,매매상품용,2012-07-01,2012-07-01,개인,12000000.0,133.0,12.3,3490.0,A0110003120993111,3800.0,None,52200000.0,기아
957089,B4S10008100004210,특수,특수용도형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2011,경유,국산,7395.0,2100.0,3320.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,인천,자가용,부활차이전등록,2020-12-01,매매상품용,2011-04-01,2011-04-01,개인,4500000.0,160.0,10.0,7985.0,A0810005009663210,2500.0,None,97200000.0,현대
979114,B3510036100004119,특수,특수용도형,소형,2497.0,2,NaN,동해고소작업차,2020,경유,국산,5380.0,1740.0,2735.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ALKXXXXXX,대전,자가용,부활차이전등록,2021-01-01,일반소유용,2020-10-01,2020-10-01,개인,40000000.0,133.0,9.9,3140.0,A0110003132223119,3600.0,4x2,40000000.0,기아
997063,B4S10010400014313,특수,특수용도형,대형,5899.0,3,NaN,호룡엘리카고가사다리차,2014,경유,국산,9930.0,2390.0,3420.0,4260.0,1870.0,1800.0,수동,KMFLA18KPECXXXXXX,경기,영업용,부활차이전등록,2021-02-01,일반소유용,2014-04-01,2014-04-01,개인,0.0,260.0,8.0,13805.0,A0810005217703312,2500.0,None,140000000.0,현대
997266,B7J10003200014212,특수,특수용도형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,7385.0,2130.0,2895.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,경기,자가용,부활차이전등록,2021-02-01,매매상품용,2013-03-01,2013-02-01,개인,38000000.0,160.0,10.0,8075.0,A0810005010433211,2500.0,None,100000000.0,현대
1020892,B7Y10002100004211,특수,특수용도형,중형,3933.0,3,NaN,다산고소작업차,2011,경유,국산,6875.0,2075.0,3185.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,인천,자가용,부활차이전등록,2021-03-01,매매상품용,2011-02-01,2011-01-01,개인,4000000.0,160.0,10.0,8145.0,A0810005009833210,2500.0,None,101000000.0,현대
1020935,B7J10003200014212,특수,특수용도형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,7385.0,2130.0,2895.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,경기,자가용,부활차이전등록,2021-03-01,매매상품용,2014-10-01,2014-09-01,법인및사업자,34000000.0,160.0,10.0,8075.0,A0810005010433211,2500.0,None,0.0,현대
1045920,B7J10002500014211,특수,특수용도형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2012,경유,국산,7395.0,2160.0,3135.0,3775.0,1665.0,1495.0,수동,KMFGA17HPCCXXXXXX,광주,자가용,부활차이전등록,2021-04-01,일반소유용,2012-02-01,2012-01-01,개인,32000000.0,160.0,10.0,8175.0,A0810005009663210,2500.0,None,107200000.0,현대
1046160,BAE10002700014115,특수,특수용도형,소형,2497.0,2,NaN,천하사다리차2,2016,경유,국산,5255.0,1750.0,2650.0,2615.0,1490.0,1340.0,수동,KNCSJZ76AGKXXXXXX,경기,영업용,부활차이전등록,2021-04-01,일반소유용,2015-10-01,2015-09-01,개인,0.0,133.0,10.0,3490.0,A0110003127053114,3800.0,None,55300000.0,기아
1046379,B9P10002400004111,특수,특수용도형,소형,2902.0,2,NaN,드림 사다리차,2011,경유,국산,5305.0,1860.0,2885.0,2615.0,1490.0,1340.0,수동,KNCSJZ74ABKXXXXXX,경기,자가용,부활차단순등록,2021-04-01,일반소유용,2011-10-01,2011-09-01,개인,0.0,126.0,11.2,3460.0,A0110003118463110,3800.0,None,54500000.0,기아
1088156,BAE10003300034218,특수,특수용도형,중형,2497.0,3,NaN,천하사다리차,2019,경유,국산,6230.0,1960.0,3120.0,2740.0,1475.0,1435.0,수동,KMFVA17RPKCXXXXXX,경기,자가용,부활차단순등록,2021-06-01,일반소유용,2019-03-01,2019-01-01,개인,87200000.0,150.0,10.9,6515.0,A0810005102573215,3300.0,4x2,87200000.0,현대
1100200,B9P10004000014215,특수,특수용도형,중형,2497.0,3,NaN,드림사다리차,2016,경유,국산,5990.0,1950.0,2860.0,2740.0,1475.0,1435.0,수동,KMFVA17RPGCXXXXXX,서울,자가용,부활차이전등록,2021-07-01,일반소유용,2016-10-01,2016-09-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,0.0,현대
1133714,B0110014800004215,특수,특수용도형,중형,3933.0,3,NaN,전진직진식활선고소작업차,2015,경유,국산,5880.0,2130.0,3630.0,2850.0,1680.0,1495.0,수동,KMFHA17GPFCXXXXXX,경기,자가용,부활차단순등록,2021-08-01,일반소유용,2015-10-01,2015-09-01,개인,140000000.0,170.0,10.6,8025.0,A0810010100633215,2500.0,None,140000000.0,현대
1184730,CFU10000100004116,특수,특수용도형,소형,2497.0,1,NaN,진보특장고소작업차,2017,경유,국산,5605.0,1740.0,2740.0,2615.0,1490.0,1340.0,수동,KNCSJX76AHKXXXXXX,경기,자가용,부활차이전등록,2021-11-01,매매상품용,2017-06-01,2017-04-01,법인및사업자,38500000.0,133.0,9.6,3485.0,A0110003128963116,3600.0,None,70000000.0,기아
1184816,B4S10008200004210,특수,특수용도형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2011,경유,국산,7315.0,2100.0,2960.0,3775.0,1665.0,1495.0,수동,KMFGA17HPBCXXXXXX,경북,자가용,부활차단순등록,2021-11-01,일반소유용,2011-02-01,2011-01-01,개인,500000.0,160.0,10.0,7835.0,A0810005009663210,2500.0,None,99500000.0,현대
1222876,B4S10009400004112,특수,특수용도형,소형,2497.0,2,NaN,호룡 엘리카 고가사다리차,2012,경유,국산,5415.0,1740.0,2720.0,2615.0,1490.0,1340.0,수동,KNCSJZ76ACKXXXXXX,경기,자가용,부활차단순등록,2022-01-01,일반소유용,2012-06-01,2012-05-01,개인,500000.0,133.0,12.3,3430.0,A0110003120993111,3800.0,None,50900000.0,기아
1235035,B7J10003200014212,특수,특수용도형,중형,3933.0,3,NaN,한신 울트라 고소작업차,2013,경유,국산,7385.0,2130.0,2895.0,3775.0,1665.0,1495.0,수동,KMFGA17HPDCXXXXXX,경기,자가용,부활차단순등록,2022-02-01,일반소유용,2013-03-01,2013-01-01,개인,0.0,160.0,10.0,8075.0,A0810005010433211,2500.0,None,98100000.0,현대
1263040,BCB10003700024317,특수,특수용도형,대형,6728.0,2,NaN,진우고소작업차,2018,경유,국산,9650.0,2495.0,3880.0,4900.0,2075.0,1760.0,수동,KLTDC4CH5JKXXXXXX,경기,자가용,부활차단순등록,2022-03-01,일반소유용,2017-07-01,2017-06-01,개인,154500000.0,280.0,6.4,16370.0,A0310009502633314,2500.0,None,154500000.0,대우
1263468,B4S10009100014211,특수,특수용도형,중형,3933.0,3,NaN,호룡 스카이 고소작업차,2012,경유,국산,7315.0,2100.0,3010.0,3775.0,1665.0,1495.0,수동,KMFGA17HPCCXXXXXX,경기,자가용,부활차단순등록,2022-03-01,일반소유용,2012-07-01,2012-06-01,개인,98100000.0,160.0,10.0,8085.0,A0810005009853210,2500.0,None,98100000.0,현대
1305475,B3510023700004216,특수,특수용도형,중형,6299.0,3,NaN,동해절연고소작업차,2017,경유,국산,6325.0,2360.0,3735.0,3300.0,1870.0,1660.0,수동,KMCLK18TPHCXXXXXX,경기,자가용,부활차단순등록,2022-05-01,일반소유용,2017-01-01,2016-12-01,개인,202000000.0,280.0,7.7,9775.0,A0810005223263316,2500.0,None,202000000.0,현대
1315459,B0W10027700004215,특수,특수용도형,중형,3933.0,3,NaN,광림절연고소작업차,2015,경유,국산,5975.0,2025.0,3560.0,2850.0,1680.0,1495.0,수동,KMFHA17GPFCXXXXXX,경기,자가용,부활차이전등록,2022-06-01,일반소유용,2015-10-01,2015-08-01,법인및사업자,0.0,170.0,10.6,7665.0,A0810010100633215,2500.0,None,141000000.0,현대

In [ ]:
# for i in range(len(new)):
#     if math.isnan(new.loc[i, 'max_load']):
#           new.loc[i, 'max_load'] = -999

In [ ]:
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                     11
width                   11
height                  11
wheelbase               96
front_wb              1411
back_wb                 97
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757369
consum_rate         754436
weight              729855
first_manage_id     765677
rpm                 757722
dri_system          743589
first_pur_amount    705041
mani                     9
dtype: int64

In [ ]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353673 entries, 0 to 1353672
Data columns (total 38 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   index             1353673 non-null  int64
 1   manage_id         1353673 non-null  object
 2   vehicle_type      1353673 non-null  object
 3   vehicle_model     1353673 non-null  object
 4   vehicle_cat       1353673 non-null  object
 5   displacement      1353673 non-null  float64
 6   passenger         1353673 non-null  int32
 7   max_load          1353589 non-null  float32
 8   vehecle_name      1353673 non-null  object
 9   model_year        1353673 non-null  int32
 10  fuel              1297220 non-null  object
 11  dom_import        1353673 non-null  object
 12  vehicle_body      1353566 non-null  object
 13  len               1353662 non-null  float32
 14  width             1353662 non-null  float32
 15  height            1353662 non-null  float32
 16  wheelbase         1353577 non-null  float32
 17  front_wb          1352262 non-null  float32
 18  back_wb           1353576 non-null  float32
 19  transmission      1353641 non-null  object
 20  vin               1353664 non-null  object
 21  reg_area          1353673 non-null  object
 22  purpose           1353673 non-null  object
 23  apply_category    1353673 non-null  object
 24  sale_reg_date     1353673 non-null  datetime64[ns]
 25  reg_detail        1353673 non-null  object
 26  first_reg_date    1353673 non-null  datetime64[ns]
 27  man_date          1353673 non-null  datetime64[ns]
 28  member_classi     1353673 non-null  object
 29  pur_amount        1353668 non-null  float64
 30  max_output        596304 non-null   float32
 31  consum_rate       599237 non-null   float32
 32  weight            623818 non-null   float32
 33  first_manage_id   587996 non-null   object
 34  rpm               595951 non-null   float32
 35  dri_system        610084 non-null   object
 36  first_pur_amount  648632 non-null   float32
 37  mani              1353664 non-null  object
dtypes: datetime64[ns](3), float32(12), float64(2), int32(2), int64(1), object(18)
memory usage: 320.2+ MB

###사용연료명(fuel)

In [ ]:
new.isnull().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56453
dom_import               0
len                      0
width                    0
height                   0
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757358
consum_rate         754425
weight              729847
first_manage_id     765666
rpm                 757711
dri_system          743579
first_pur_amount    705033
mani                     9
dtype: int64

In [ ]:
new[new.displacement == 0].shape

(56517, 36)

In [ ]:
new[(new.fuel.isnull())].shape

(56447, 33)

In [ ]:
new[(new.displacement == 0) & (new.fuel.isnull())].shape

(56447, 33)

In [ ]:
new[(new.fuel.isnull()) & (new.displacement > 0)]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
545345,B6F10001600003219,화물,특수용도형-특수용도형,중형,3933.0,3,2300.0,나인2.3톤냉동탑,2019,None,국산,7625.0,2495.0,2780.0,수동,KMFHA17GPKCXXXXXX,충남,영업용,신조차 신규등록,2019-05-01,일반소유용,2019-05-01,2019-05-01,법인및사업자,69800000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
687107,B5S20000200003219,화물,특수용도형-특수용도형,중형,5193.0,3,2200.0,제일2.2톤냉동탑,2019,None,외산,7065.0,2450.0,3150.0,자동,JAANPR75KK7XXXXXX,경기,영업용,수입차 신규등록,2019-12-01,일반소유용,2019-12-01,2019-11-01,법인및사업자,70800000.0,NaN,NaN,NaN,None,NaN,None,NaN,아우디
991688,B6220001300003321,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2020,None,외산,12945.0,2495.0,3980.0,None,WMA41SZZ8LPXXXXXX,광주,영업용,수입차 신규등록,2021-02-01,일반소유용,2021-02-01,2021-02-01,법인및사업자,275900000.0,510.0,3.4,39970.0,01650002300143020,1800.0,10x4,275900000.0,현대
1080267,B6220001300013321,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2021,None,외산,12945.0,2495.0,3980.0,자동,WMA41SZZ5MYXXXXXX,서울,영업용,수입차 신규등록,2021-06-01,일반소유용,2021-06-01,2021-06-01,법인및사업자,258900000.0,510.0,3.4,39970.0,01650002300143020,1800.0,10x4,258900000.0,현대
1127585,B6220001300013321,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2021,None,외산,12945.0,2495.0,3980.0,자동,WMA41SZZ5MLXXXXXX,서울,영업용,수입차 신규등록,2021-08-01,일반소유용,2021-08-01,2021-07-01,법인및사업자,276500000.0,510.0,3.4,39970.0,01650002300143020,1800.0,10x4,276500000.0,현대
1177966,B6220001300023321,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2022,None,외산,12945.0,2495.0,3980.0,자동,WMA41SZZ1NLXXXXXX,대전,영업용,수입차 신규등록,2021-11-01,일반소유용,2021-11-01,2021-10-01,법인및사업자,234600000.0,510.0,3.4,39970.0,01650002300143020,1800.0,10x4,234600000.0,현대

In [ ]:
# '나인2.3톤냉동탑', '제일2.2톤냉동탑', '한국MAN23.8톤상승윙바디' 최빈값 경유사용
new.loc[(new.displacement != 0) & (new.fuel.isnull()) & (new.vehicle_name == '나인2.3톤냉동탑'), 'fuel'] = '경유'
new.loc[(new.displacement != 0) & (new.fuel.isnull()) & (new.vehicle_name == '제일2.2톤냉동탑'), 'fuel'] = '경유'
new.loc[(new.displacement != 0) & (new.fuel.isnull()) & (new.vehicle_name == '한국MAN23.8톤상승윙바디'), 'fuel'] = '경유'

In [ ]:
new[(new.vehicle_name.str.contains('한국MAN23.8톤상승윙바디'))].head()

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
258480,B6220000100003318,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2018,경유,외산,12985.0,2495.0,3940.0,자동,WMA41SZZ5JYXXXXXX,경기,영업용,수입차 신규등록,2018-04-01,일반소유용,2018-04-01,2018-03-01,법인및사업자,262000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
266997,B6220000100003318,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2018,경유,외산,12985.0,2495.0,3940.0,자동,WMA41SZZ5JYXXXXXX,경기,영업용,수입차 신규등록,2018-04-01,일반소유용,2018-04-01,2018-04-01,법인및사업자,262000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
267044,B6220000100003318,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2018,경유,외산,12985.0,2495.0,3940.0,자동,WMA41SZZ4JYXXXXXX,경기,영업용,수입차 신규등록,2018-04-01,일반소유용,2018-04-01,2018-04-01,법인및사업자,262000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
370250,B6220000100003318,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2018,경유,외산,12985.0,2495.0,3940.0,자동,WMA41SZZ0JYXXXXXX,경기,영업용,수입차 신규등록,2018-09-01,일반소유용,2018-09-01,2018-05-01,법인및사업자,263000000.0,NaN,NaN,NaN,None,NaN,None,NaN,현대
751557,B6220000100013320,화물,특수용도형-특수용도형,대형,12419.0,2,23800.0,한국MAN23.8톤상승윙바디,2019,경유,외산,12985.0,2495.0,3940.0,자동,WMA41SZZ1KYXXXXXX,충북,영업용,수입차 신규등록,2020-03-01,일반소유용,2020-03-01,2020-02-01,법인및사업자,270900000.0,500.0,3.4,39990.0,01650002300023017,1800.0,10x4,270900000.0,현대

### 차체길이(len), 너비(width), 높이(height) 결측치

In [ ]:
new.isnull().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 56447
dom_import               0
len                      0
width                    0
height                   0
transmission            32
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               5
max_output          757358
consum_rate         754425
weight              729847
first_manage_id     765666
rpm                 757711
dri_system          743579
first_pur_amount    705033
mani                     9
dtype: int64

In [ ]:
new.columns

Index(['manage_id', 'vehicle_type', 'vehicle_model', 'vehicle_cat',
       'displacement', 'passenger', 'max_load', 'vehicle_name', 'model_year',
       'fuel', 'dom_import', 'len', 'width', 'height', 'transmission', 'vin',
       'reg_area', 'purpose', 'apply_category', 'sale_reg_date', 'reg_detail',
       'first_reg_date', 'man_date', 'member_classi', 'pur_amount',
       'max_output', 'consum_rate', 'weight', 'first_manage_id', 'rpm',
       'dri_system', 'first_pur_amount', 'mani'],
      dtype='object')

In [ ]:
new.dropna(subset=['len', 'width', 'height'], axis=0, inplace=True)
new.reset_index(inplace = True, drop = True)

### 변속기종류명(transmission)

### 취득금액(pur_amount) 결측치

In [ ]:
new.dropna(subset=['pur_amount'], axis=0, inplace=True)
new.reset_index(inplace = True, drop = True)

In [ ]:
new[new.pur_amount.isnull()]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
116332,A0110002100393203,화물,밴,중형,2902.0,6,800.0,봉고Ⅲ 밴,2004,경유,국산,4900.0,1810.0,1980.0,자동,KN3HNS5N24XXXXXX,인천,자가용,부활차단순등록,2017-09-01,일반소유용,2004-07-01,2004-05-01,개인,NaN,NaN,NaN,NaN,None,NaN,None,NaN,기아
191138,A0810006201443104,화물,일반형-카고,소형,2497.0,3,1000.0,포터Ⅱ(PORTERⅡ),2005,경유,국산,5160.0,1740.0,1965.0,수동,KMFZCS7JP5XXXXXX,경기,자가용,부활차단순등록,2018-01-01,일반소유용,2006-02-01,2005-10-01,개인,NaN,NaN,NaN,NaN,None,NaN,None,NaN,현대
447820,B0910002200023305,화물,특수용도형-특수용도형,대형,0.0,0,27000.0,미래40피트구즈넥콘테이너샤시,2006,None,국산,12480.0,2440.0,1530.0,기타,KN9DNEXTZ6UXXXXXX,부산,자가용,부활차단순등록,2019-01-01,일반소유용,2006-07-01,2006-03-01,개인,NaN,NaN,NaN,NaN,None,NaN,None,NaN,기아
636525,A0810006207253108,화물,일반형-카고,소형,2497.0,3,1000.0,포터Ⅱ(PORTERⅡ),2009,경유,국산,5120.0,1740.0,1965.0,수동,KMFZCN7JP9UXXXXXX,서울,자가용,부활차단순등록,2019-09-01,일반소유용,2008-11-01,2008-11-01,개인,NaN,NaN,NaN,NaN,None,NaN,None,NaN,현대
690166,A0810006201173204,화물,일반형-카고,중형,2476.0,6,1000.0,포터Ⅱ(PORTERⅡ),2005,경유,국산,5120.0,1740.0,1965.0,수동,KMFZCD7HP5UXXXXXX,인천,자가용,부활차단순등록,2019-12-01,일반소유용,2005-09-01,2005-09-01,개인,NaN,NaN,NaN,NaN,None,NaN,None,NaN,현대

In [ ]:
new.shape

(1353668, 37)

In [ ]:
new.isna().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                 0
vehecle_name             0
model_year               0
fuel                 55138
dom_import               0
len                      0
width                    0
height                   0
wheelbase                0
front_wb                 0
back_wb                  0
transmission            29
vin                      9
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               0
max_output          755953
consum_rate         753389
weight              729029
first_manage_id     764680
rpm                 756306
dri_system          742655
first_pur_amount    704242
mani                     9
dtype: int64

In [ ]:
new[new.transmission.isna()].head(1) # 트레일러/ 팔레트 / 컨테이너, na 날림

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehecle_name,model_year,fuel,dom_import,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
39225,BPF10000200013317,화물,특수용도형-피견인,대형,0.0,0,26500.0,만금26.5톤아스팔트탱크트레일러,2017,None,국산,11390.0,2490.0,3605.0,8900.0,0.0,1850.0,None,KN9ANEZTZHXXXXXX,인천,영업용,신조차 신규등록,2017-05-01,일반소유용,2017-05-01,2017-05-01,법인및사업자,56000000.0,NaN,NaN,NaN,None,NaN,None,NaN,기아

###차대번호(vin) 결측치

In [ ]:
new.isnull().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                 0
vehecle_name             0
model_year               0
fuel                 55133
dom_import               0
len                      0
width                    0
height                   0
wheelbase                0
front_wb                 0
back_wb                  0
transmission            29
vin                      0
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               0
max_output          755945
consum_rate         753382
weight              729022
first_manage_id     764671
rpm                 756298
dri_system          742646
first_pur_amount    704235
mani                     0
dtype: int64

In [ ]:
new.dropna(subset=['vin'], axis=0, inplace=True)

In [ ]:
new[new.vin.isnull()]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehecle_name,model_year,fuel,dom_import,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,reg_detail,first_reg_date,man_date,member_classi,pur_amount,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount,mani
110740,10173900000000,화물,특수용도형-특수용도형,대형,7545.0,5,3000.0,우리소방펌프자동차,2001,경유,국산,7630.0,2240.0,2800.0,4260.0,1770.0,1660.0,수동,None,인천,자가용,부활차이전등록,2017-09-01,일반소유용,2001-03-01,2001-03-01,개인,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
113350,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,자가용,부활차단순등록,2017-09-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
126212,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,자가용,부활차단순등록,2017-09-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
156130,10206700000000,화물,특수용도형-특수용도형,중형,2957.0,3,1000.0,대동봉고프런티어 킹캡윙바디,2002,경유,국산,5105.0,1800.0,2550.0,2585.0,1490.0,1350.0,수동,None,대구,자가용,부활차단순등록,2017-11-01,일반소유용,2002-11-01,2002-11-01,개인,0.0,NaN,NaN,NaN,None,NaN,None,NaN,None
209133,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,영업용,부활차이전등록,2018-02-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
211512,10166700000000,화물,특수용도형-특수용도형,대형,0.0,0,26000.0,미래40피트콤비네이션콘테이너샤시,2002,None,국산,12400.0,2410.0,1470.0,10300.0,0.0,1820.0,기타,None,인천,영업용,부활차이전등록,2018-02-01,일반소유용,2002-02-01,2002-02-01,법인및사업자,1000000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
509459,10122600000000,화물,특수용도형-특수용도형,중형,3581.0,3,2000.0,한성2000L다목적방제차,2000,경유,국산,5230.0,1965.0,2690.0,2760.0,1470.0,1490.0,수동,None,광주,자가용,부활차단순등록,2019-03-01,일반소유용,2000-09-01,2000-09-01,개인,2800000.0,NaN,NaN,NaN,None,NaN,None,NaN,None
778657,10165100000000,화물,특수용도형-특수용도형,대형,0.0,0,27500.0,미래40피트구즈넥콘테이너샤시,2002,None,국산,12480.0,2440.0,1530.0,10500.0,0.0,1820.0,기타,None,경기,자가용,부활차단순등록,2020-04-01,일반소유용,2003-02-01,2002-12-01,법인및사업자,0.0,NaN,0.0,30950.0,None,NaN,None,0.0,None
1133608,20098100000000,화물,특수용도형-특수용도형,중형,5958.0,3,2500.0,유니목1200,2001,경유,외산,4470.0,2110.0,2620.0,2650.0,1660.0,1680.0,수동,None,경남,자가용,부활차이전등록,2021-08-01,일반소유용,1991-08-01,1991-08-01,개인,0.0,126.0,8.2,7285.0,None,2400.0,None,0.0,None

In [ ]:
new.isnull().sum()

manage_id                0
vehicle_type             0
vehicle_model            0
vehicle_cat              0
displacement             0
passenger                0
max_load                84
vehicle_name             0
model_year               0
fuel                 55133
dom_import               0
len                      0
width                    0
height                   0
wheelbase                0
front_wb                 0
back_wb                  0
transmission            29
vin                      0
reg_area                 0
purpose                  0
apply_category           0
sale_reg_date            0
reg_detail               0
first_reg_date           0
man_date                 0
member_classi            0
pur_amount               0
max_output          755945
consum_rate         753382
weight              729022
first_manage_id     764671
rpm                 756298
dri_system          742646
first_pur_amount    704235
mani                     0
dtype: int64

### parquet파일로 불러오기

In [ ]:
new.to_parquet('new1.parquet', index = False)

In [ ]:
pd.read_parquet('new1.parquet').head()