In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
plt.rcParams['font.family'] = 'AppleGothic'
pd.set_option('display.max_columns', None)

In [7]:
transfer = pd.read_parquet('transfer.parquet')
cancel = pd.read_parquet('cancel.parquet')

In [8]:
transfer.drop(['원동기형식명', '사용본거지주소명','제원모델년도', '소유자주소명', '회원등록번호','변경전사용본거지주소명', '차량등록번호','사용본거지주소명', '소유자주소명', '차량중량'],axis=1, inplace=True)
transfer.drop(['타이어전전형식', '타이어전후형식','타이어후전형식','타이어후중형식','타이어후후형식'],axis=1, inplace=True)

In [9]:
transfer.이전등록구분명.unique()

['당사자거래이전', '매매업자거래이전', '상속이전', '촉탁이전', '기타이전', '증여이전']
Categories (6, object): ['기타이전', '당사자거래이전', '매매업자거래이전', '상속이전', '증여이전', '촉탁이전']

In [10]:
newcol = list(set(transfer.columns)-set(cancel.columns))

In [11]:
newdf = transfer.loc[:,newcol]

In [12]:
newdf.columns

Index(['이전등록구분명', '변경전회원구분명', '매매상품구분명', '취득금액', '변경전등록상세명', '변경전회원등록번호',
       '변경전매매상품구분명'],
      dtype='object')

In [13]:
df = newdf
(df.isnull().sum() / len(df))*100

이전등록구분명        0.000000
변경전회원구분명       0.000000
매매상품구분명       69.320157
취득금액           0.000132
변경전등록상세명       0.000000
변경전회원등록번호     31.052737
변경전매매상품구분명    71.308639
dtype: float64

In [8]:
transfer[(transfer['변경전회원구분명'] == '법인및사업자') & (transfer['변경전회원등록번호'].notna())]

Empty DataFrame
Columns: [제원관리번호, 차종명, 차종유형명, 차종분류명, 형식명, 배기량, 승차정원수, 최대적재량, 차명, 모델연도, 사용연료명, 국산수입구분명, 차대차체형상명, 차체길이, 차체너비, 차체높이, 축간거리, 전윤간거리, 후윤간거리, 변속기종류명, 차대번호, 등록관청명, 용도구분명, 신청구분명, 등록일, 이전등록구분명, 등록상세명, 매매상품구분명, 변경전등록상세명, 변경전매매상품구분명, 최초등록일, 제작년월일, 회원구분명, 취득금액, 주행거리, 변경전회원구분명, 변경전회원등록번호, 원동기최고출력, 연료소비율, 차량총중량, 최초제원관리번호, 원동기RPM값, 구동방식코드, 최초취득금액]
Index: []

In [9]:
transfer[(transfer['변경전회원구분명'] == '개인') & (transfer['변경전회원등록번호'].isna())]

Empty DataFrame
Columns: [제원관리번호, 차종명, 차종유형명, 차종분류명, 형식명, 배기량, 승차정원수, 최대적재량, 차명, 모델연도, 사용연료명, 국산수입구분명, 차대차체형상명, 차체길이, 차체너비, 차체높이, 축간거리, 전윤간거리, 후윤간거리, 변속기종류명, 차대번호, 등록관청명, 용도구분명, 신청구분명, 등록일, 이전등록구분명, 등록상세명, 매매상품구분명, 변경전등록상세명, 변경전매매상품구분명, 최초등록일, 제작년월일, 회원구분명, 취득금액, 주행거리, 변경전회원구분명, 변경전회원등록번호, 원동기최고출력, 연료소비율, 차량총중량, 최초제원관리번호, 원동기RPM값, 구동방식코드, 최초취득금액]
Index: []

In [14]:
transfer

,제원관리번호,차종명,차종유형명,차종분류명,형식명,배기량,승차정원수,최대적재량,차명,모델연도,사용연료명,국산수입구분명,차대차체형상명,차체길이,차체너비,차체높이,축간거리,전윤간거리,후윤간거리,변속기종류명,차대번호,등록관청명,용도구분명,신청구분명,등록일,이전등록구분명,등록상세명,매매상품구분명,변경전등록상세명,변경전매매상품구분명,최초등록일,제작년월일,회원구분명,취득금액,주행거리,변경전회원구분명,변경전회원등록번호,원동기최고출력,연료소비율,차량총중량,최초제원관리번호,원동기RPM값,구동방식코드,최초취득금액
0,10007400060000,특수,구난,중형,KB940S-WR,10350.0,3.0,5000.0,기아마스타5톤렉카,2000,경유,국산,캡오바,8230.0,2465.0,2830.0,4640.0,1985.0,1840.0,수동,NaN,울산,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,198008,198008.0,개인,0.0,451000.0,개인,40대 여자,236.0,16.200001,11239.0,NaN,2200.0,NaN,NaN
1,10161000000000,특수,구난,중형,SW203,3907.0,3.0,1100.0,수성중형렉커트럭,2000,경유,국산,캡오버형,6395.0,2000.0,2690.0,3570.0,1665.0,1495.0,수동,NaN,경북,자가용,단순이전,202001,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,200007,200006.0,법인및사업자,2000000.0,301000.0,법인및사업자,NaN,155.0,10.000000,6025.0,NaN,3200.0,NaN,0.0
2,10149600030000,특수,구난,중형,SW500-1N,6606.0,3.0,1500.0,수성5톤슈퍼렉커트럭,2001,경유,국산,"ㄷ형프레임,캡오버형",7605.0,2195.0,3030.0,4260.0,1795.0,1660.0,수동,NaN,제주,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200103,200102.0,개인,0.0,198000.0,법인및사업자,NaN,225.0,8.100000,9985.0,NaN,2500.0,NaN,NaN
3,10156400020000,특수,구난,중형,KJW-HL112,2476.0,3.0,500.0,국제렉커차,2000,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200009,200008.0,법인및사업자,0.0,274000.0,법인및사업자,NaN,103.0,13.600000,3105.0,NaN,3800.0,NaN,0.0
4,10156400030000,특수,구난,소형,KJW-HL113,2476.0,3.0,500.0,국제렉커차,2002,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200201,200112.0,개인,500000.0,151000.0,개인,50대 남자,103.0,13.600000,3415.0,NaN,3800.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512757,BFM20038600003320,화물,일반형-카고,대형,HS9.5T-MAN86,6871.0,2.0,6900.0,한성9.5톤카고,2020,경유,외산,ㄷ자형프레임캡오버형,11195.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ4LYXXXXXX,경북,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,202010,202010.0,개인,75500000.0,168000.0,법인및사업자,NaN,290.0,5.700000,18120.0,01650003300263018,2200.0,6x2,121800000.0
1512758,BXH20015200013318,화물,일반형-카고,대형,HJ8.5T-M6X2,6871.0,2.0,6000.0,한중8.5톤카고,2019,경유,외산,ㄷ자형프레임캡오버형,10660.0,2495.0,3220.0,6175.0,2065.0,1810.0,자동,WMAN18ZZ6KYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201907,201907.0,법인및사업자,0.0,345000.0,법인및사업자,NaN,290.0,5.700000,17070.0,01650003300013017,2200.0,6x2,117200000.0
1512759,C0120008200003320,화물,일반형-카고,대형,M6.5T-MANH-5775,6871.0,2.0,4200.0,메리트6.5톤트럭,2020,경유,외산,ㄷ자형프레임캡오버형,10045.0,2495.0,3220.0,5775.0,2065.0,1810.0,자동,WMAN18ZZ6LYXXXXXX,경북,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,202006,202005.0,법인및사업자,0.0,186000.0,법인및사업자,NaN,290.0,5.700000,14790.0,01650003300173018,2200.0,6x2,119800000.0
1512760,BXH20010200003317,화물,특수용도형-특수용도형,대형,HJ11M-MAN11.5,6871.0,2.0,11000.0,한중11톤냉장윙바디,2017,경유,외산,ㄷ자형프레임캡오버형,12905.0,2495.0,3920.0,6975.0,2070.0,1815.0,자동,WMAN18ZZ7HYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201801,201711.0,개인,0.0,532000.0,개인,40대 여자,341.0,4.500000,24790.0,01620001700123317,2200.0,NaN,202000000.0
1512761,BFM20015000003317,화물,일반형-카고,대형,HS9.5T-MAN88,6871.0,2.0,7300.0,한성9.5톤만카고,2017,경유,외산,ㄷ자형프레임캡오버형,11320.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ9HYXXXXXX,대전,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,201708,201708.0,법인및사업자,42000000.0,529000.0,법인및사업자,NaN,290.0,5.500000,18550.0,01620003300193316,2200.0,NaN,109900000.0

In [10]:
df1 = (transfer[(transfer['이전등록구분명'] == '당사자거래이전') & (transfer['변경전회원구분명'] == '법인및사업자')]).loc[:,['변경전매매상품구분명','매매상품구분명']]

In [11]:
df1['변경전매매상품구분명'].unique()

[NaN, '상품용']
Categories (1, object): ['상품용']

In [12]:
df1[(df1['변경전매매상품구분명'].isna())]['매매상품구분명'].unique()

[NaN, '상품용']
Categories (1, object): ['상품용']

In [13]:
df1[df1['변경전매매상품구분명'] == '상품용']['매매상품구분명'].unique()

[NaN, '상품용']
Categories (1, object): ['상품용']

In [14]:
kor = transfer.columns

In [15]:
engcol= ['manage_id', 'vehicle_type', 'vehicle_model', 'vehicle_cat','engine', 'displacement', 'passenger','max_load', 'vehicle_name', 
         'model_year', 'fuel','dom_import', 'vehicle_body', 'len', 'width', 'height', 'wheelbase',
         'front_wb', 'back_wb', 'transmission', 'vin','reg_area','purpose','apply_category','sale_reg_date', 
         'tranfer_reg_cat','reg_detail','product_cat','before_reg_detail','before_product_cat','first_reg_date',
         'man_date', 'member_classi','pur_amount','mileage','before_member_classi','before_member_num','max_output', 
         'consum_rate', 'weight', 'first_manage_id', 'rpm', 'dri_system','first_pur_amount']

In [16]:
transfer.columns = engcol

In [17]:
transfer

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
0,10007400060000,특수,구난,중형,KB940S-WR,10350.0,3.0,5000.0,기아마스타5톤렉카,2000,경유,국산,캡오바,8230.0,2465.0,2830.0,4640.0,1985.0,1840.0,수동,NaN,울산,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,198008,198008.0,개인,0.0,451000.0,개인,40대 여자,236.0,16.200001,11239.0,NaN,2200.0,NaN,NaN
1,10161000000000,특수,구난,중형,SW203,3907.0,3.0,1100.0,수성중형렉커트럭,2000,경유,국산,캡오버형,6395.0,2000.0,2690.0,3570.0,1665.0,1495.0,수동,NaN,경북,자가용,단순이전,202001,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,200007,200006.0,법인및사업자,2000000.0,301000.0,법인및사업자,NaN,155.0,10.000000,6025.0,NaN,3200.0,NaN,0.0
2,10149600030000,특수,구난,중형,SW500-1N,6606.0,3.0,1500.0,수성5톤슈퍼렉커트럭,2001,경유,국산,"ㄷ형프레임,캡오버형",7605.0,2195.0,3030.0,4260.0,1795.0,1660.0,수동,NaN,제주,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200103,200102.0,개인,0.0,198000.0,법인및사업자,NaN,225.0,8.100000,9985.0,NaN,2500.0,NaN,NaN
3,10156400020000,특수,구난,중형,KJW-HL112,2476.0,3.0,500.0,국제렉커차,2000,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200009,200008.0,법인및사업자,0.0,274000.0,법인및사업자,NaN,103.0,13.600000,3105.0,NaN,3800.0,NaN,0.0
4,10156400030000,특수,구난,소형,KJW-HL113,2476.0,3.0,500.0,국제렉커차,2002,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200201,200112.0,개인,500000.0,151000.0,개인,50대 남자,103.0,13.600000,3415.0,NaN,3800.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512757,BFM20038600003320,화물,일반형-카고,대형,HS9.5T-MAN86,6871.0,2.0,6900.0,한성9.5톤카고,2020,경유,외산,ㄷ자형프레임캡오버형,11195.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ4LYXXXXXX,경북,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,202010,202010.0,개인,75500000.0,168000.0,법인및사업자,NaN,290.0,5.700000,18120.0,01650003300263018,2200.0,6x2,121800000.0
1512758,BXH20015200013318,화물,일반형-카고,대형,HJ8.5T-M6X2,6871.0,2.0,6000.0,한중8.5톤카고,2019,경유,외산,ㄷ자형프레임캡오버형,10660.0,2495.0,3220.0,6175.0,2065.0,1810.0,자동,WMAN18ZZ6KYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201907,201907.0,법인및사업자,0.0,345000.0,법인및사업자,NaN,290.0,5.700000,17070.0,01650003300013017,2200.0,6x2,117200000.0
1512759,C0120008200003320,화물,일반형-카고,대형,M6.5T-MANH-5775,6871.0,2.0,4200.0,메리트6.5톤트럭,2020,경유,외산,ㄷ자형프레임캡오버형,10045.0,2495.0,3220.0,5775.0,2065.0,1810.0,자동,WMAN18ZZ6LYXXXXXX,경북,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,202006,202005.0,법인및사업자,0.0,186000.0,법인및사업자,NaN,290.0,5.700000,14790.0,01650003300173018,2200.0,6x2,119800000.0
1512760,BXH20010200003317,화물,특수용도형-특수용도형,대형,HJ11M-MAN11.5,6871.0,2.0,11000.0,한중11톤냉장윙바디,2017,경유,외산,ㄷ자형프레임캡오버형,12905.0,2495.0,3920.0,6975.0,2070.0,1815.0,자동,WMAN18ZZ7HYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201801,201711.0,개인,0.0,532000.0,개인,40대 여자,341.0,4.500000,24790.0,01620001700123317,2200.0,NaN,202000000.0
1512761,BFM20015000003317,화물,일반형-카고,대형,HS9.5T-MAN88,6871.0,2.0,7300.0,한성9.5톤만카고,2017,경유,외산,ㄷ자형프레임캡오버형,11320.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ9HYXXXXXX,대전,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,201708,201708.0,법인및사업자,42000000.0,529000.0,법인및사업자,NaN,290.0,5.500000,18550.0,01620003300193316,2200.0,NaN,109900000.0

In [18]:
columns = {k:eng for k,eng in zip(kor,engcol)}

In [19]:
columns

{'제원관리번호': 'manage_id',
 '차종명': 'vehicle_type',
 '차종유형명': 'vehicle_model',
 '차종분류명': 'vehicle_cat',
 '형식명': 'engine',
 '배기량': 'displacement',
 '승차정원수': 'passenger',
 '최대적재량': 'max_load',
 '차명': 'vehicle_name',
 '모델연도': 'model_year',
 '사용연료명': 'fuel',
 '국산수입구분명': 'dom_import',
 '차대차체형상명': 'vehicle_body',
 '차체길이': 'len',
 '차체너비': 'width',
 '차체높이': 'height',
 '축간거리': 'wheelbase',
 '전윤간거리': 'front_wb',
 '후윤간거리': 'back_wb',
 '변속기종류명': 'transmission',
 '차대번호': 'vin',
 '등록관청명': 'reg_area',
 '용도구분명': 'purpose',
 '신청구분명': 'apply_category',
 '등록일': 'sale_reg_date',
 '이전등록구분명': 'tranfer_reg_cat',
 '등록상세명': 'reg_detail',
 '매매상품구분명': 'product_cat',
 '변경전등록상세명': 'before_reg_detail',
 '변경전매매상품구분명': 'before_product_cat',
 '최초등록일': 'first_reg_date',
 '제작년월일': 'man_date',
 '회원구분명': 'member_classi',
 '취득금액': 'pur_amount',
 '주행거리': 'mileage',
 '변경전회원구분명': 'before_member_classi',
 '변경전회원등록번호': 'before_member_num',
 '원동기최고출력': 'max_output',
 '연료소비율': 'consum_rate',
 '차량총중량': 'weight',
 '최초제원관리번호': 'first_manage_id',
 '원동기RPM값': 'rpm',
 '구동방식코드': 'dri_system',
 '최초취득금액': 'first_pur_amount'}

In [20]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                 138
engine                      196
displacement               8441
passenger                   760
max_load                    145
vehicle_name                  0
model_year                    0
fuel                      46335
dom_import                    0
vehicle_body                935
len                           6
width                         6
height                        7
wheelbase                    21
front_wb                    792
back_wb                      30
transmission                149
vin                        2816
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1048649
before_reg_detail             0
before_product_cat      1078730
first_reg_date                0
man_date                   5864
member_classi                 0
pur_amount                    2
mileage                   47582
before_member_classi          0
before_member_num        469754
max_output                43075
consum_rate               22510
weight                        2
first_manage_id          148165
rpm                       43487
dri_system              1302791
first_pur_amount          42189
dtype: int64

# VEHICLE_CAT
### manage_id / engine / vin 을 토대로 결측치 제거 
### 해당 함수 하나로 만들 수 있을 것 같긴한데 헷갈림..

In [21]:
vcmi = transfer[(transfer['vehicle_cat'].isna())]['manage_id'].tolist()
for i in range(len(vcmi)):
    t = transfer.loc[(transfer['manage_id'] == vcmi[i])]['vehicle_cat']
    if len(t.unique()) <= 1:
        continue
    transfer.loc[(transfer['vehicle_cat'].isna()) & (transfer['manage_id'] == vcmi[i]),'vehicle_cat'] = t.mode()[0]

In [22]:
vcengine = transfer[(transfer['vehicle_cat'].isna())]['engine'].tolist()
for i in range(len(vcengine)):
    t = transfer.loc[(transfer['engine'] == vcengine[i])]['vehicle_cat']
    if len(t.unique()) <= 1:
        continue
    transfer.loc[(transfer['vehicle_cat'].isna()) & (transfer['engine'] == vcengine[i]),'vehicle_cat'] = t.mode()[0]

In [23]:
vcvin = transfer[(transfer['vehicle_cat'].isna())]['vin'].tolist()
for i in range(len(vcvin)):
    t = transfer.loc[(transfer['vin'] == vcvin[i])]['vehicle_cat']
    if len(t.unique()) <= 1:
        continue
    transfer.loc[(transfer['vehicle_cat'].isna()) & (transfer['vin'] == vcvin[i]),'vehicle_cat'] = t.mode()[0]

In [24]:
transfer[(transfer['vehicle_cat'].isna()) & (~transfer['vehicle_name'].str.contains('트레일'))]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
189887,10049000000000,화물,특수용도형-피견인,NaN,JCG-20XEE,0.0,0.0,20500.0,진도20피트구즈넥샤시,2000,NaN,국산,피견인형,8660.0,2480.0,1560.0,7450.0,0.0,1820.0,기타,KR1GDAHX2VBXXXXXX,인천,영업용,단순이전,202004,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199901,199712.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,24300.0,NaN,NaN,NaN,0.0
726764,10049000000000,화물,특수용도형-피견인,NaN,JCG-20XEE,0.0,0.0,20500.0,진도20피트구즈넥샤시,2001,NaN,국산,피견인형,8660.0,2480.0,1560.0,7450.0,0.0,1820.0,기타,KR1GDAHX2VBXXXXXX,인천,영업용,단순이전,202103,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199901,199712.0,법인및사업자,1500000.0,1000.0,법인및사업자,NaN,NaN,0.0,24300.0,NaN,NaN,NaN,0.0
1134150,10056400000000,화물,특수용도형-피견인,NaN,ICGC-40GA,0.0,0.0,27500.0,인정40피트구즈넥샤시,2001,NaN,국산,피견인형,12450.0,2445.0,1635.0,10430.0,0.0,1820.0,기타,KMV4CD3NOSHXXXXXX,경기,영업용,단순이전,202112,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199511,199511.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,31000.0,NaN,NaN,NaN,0.0

In [25]:
def fillfunc(col,tool, transfer=transfer):
    mi = set(transfer[(transfer[col].isna())][tool].tolist())
    for i in mi:
        t = transfer.loc[(transfer[tool] == i)][col]
        if len(t.unique()) <= 1:
            continue
        transfer.loc[(transfer[col].isna()) & (transfer[tool] == i), col] = t.mode()[0]

In [26]:
nacol = ['displacement','passenger','max_load','vehicle_name','model_year','fuel','dom_import','len','width','transmission','consum_rate','weight','rpm']
tool = ['manage_id','engine','vin']

In [27]:
set(transfer[(transfer['passenger'].isna())]['manage_id'].tolist())

{'A0110003124693113',
 'A0110003125753113',
 'A0110003127053114',
 'A0110003127303114',
 'A0110003127323114',
 'A0110003128003115',
 'A0110003128023115',
 'A0110003128743115',
 'A0110003128993116',
 'A0110003129013116',
 'A0110003129793116',
 'A0110003129963117',
 'A0110003129993117',
 'A0110003130013117',
 'A0110003131073118',
 'A0110003131093118',
 'A0110003132233119',
 'A0110003132313119',
 'A0110003133043119',
 'A0110003133253120',
 'A0110003302523213',
 'A0110003302973217',
 'A0810006213013113',
 'A0810006213023113',
 'A0810006213033113',
 'A0810006213043113',
 'A0810006213613113',
 'A0810006214163114',
 'A0810006214183114',
 'A0810006214193114',
 'A0810006214783114',
 'A0810006215333115',
 'A0810006215343115',
 'A0810006215353115',
 'A0810006215363115',
 'A0810006216663116',
 'A0810006216673116',
 'A0810006217283117',
 'A0810006217293117',
 'A0810006217303117',
 'A0810006217983118',
 'A0810006218003118',
 'A0810006218803119',
 'A0810006219043119',
 'A0810006219273119',
 'A0810006219283120',
 'A0810006221283121',
 'B0910000800003303',
 'C9T10000100003115'}

In [28]:
for i in nacol:
    for k in tool:
        fillfunc(i,k)

In [29]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                  29
engine                      196
displacement                978
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      27507
dom_import                    0
vehicle_body                935
len                           3
width                         3
height                        7
wheelbase                    21
front_wb                    792
back_wb                      30
transmission                 21
vin                        2816
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1048649
before_reg_detail             0
before_product_cat      1078730
first_reg_date                0
man_date                   5864
member_classi                 0
pur_amount                    2
mileage                   47582
before_member_classi          0
before_member_num        469754
max_output                43075
consum_rate                6457
weight                        1
first_manage_id          148165
rpm                       22374
dri_system              1302791
first_pur_amount          42189
dtype: int64

In [30]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                  29
engine                      196
displacement                978
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      27507
dom_import                    0
vehicle_body                935
len                           3
width                         3
height                        7
wheelbase                    21
front_wb                    792
back_wb                      30
transmission                 21
vin                        2816
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1048649
before_reg_detail             0
before_product_cat      1078730
first_reg_date                0
man_date                   5864
member_classi                 0
pur_amount                    2
mileage                   47582
before_member_classi          0
before_member_num        469754
max_output                43075
consum_rate                6457
weight                        1
first_manage_id          148165
rpm                       22374
dri_system              1302791
first_pur_amount          42189
dtype: int64

In [31]:
transfer[(~transfer['vehicle_name'].str.contains('트레일'))& (~transfer['vehicle_name'].str.contains('샤시'))
        & (~transfer['vehicle_name'].str.contains('샤시'))]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
0,10007400060000,특수,구난,중형,KB940S-WR,10350.0,3.0,5000.0,기아마스타5톤렉카,2000,경유,국산,캡오바,8230.0,2465.0,2830.0,4640.0,1985.0,1840.0,수동,NaN,울산,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,198008,198008.0,개인,0.0,451000.0,개인,40대 여자,236.0,16.200001,11239.0,NaN,2200.0,NaN,NaN
1,10161000000000,특수,구난,중형,SW203,3907.0,3.0,1100.0,수성중형렉커트럭,2000,경유,국산,캡오버형,6395.0,2000.0,2690.0,3570.0,1665.0,1495.0,수동,NaN,경북,자가용,단순이전,202001,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,200007,200006.0,법인및사업자,2000000.0,301000.0,법인및사업자,NaN,155.0,10.000000,6025.0,NaN,3200.0,NaN,0.0
2,10149600030000,특수,구난,중형,SW500-1N,6606.0,3.0,1500.0,수성5톤슈퍼렉커트럭,2001,경유,국산,"ㄷ형프레임,캡오버형",7605.0,2195.0,3030.0,4260.0,1795.0,1660.0,수동,NaN,제주,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200103,200102.0,개인,0.0,198000.0,법인및사업자,NaN,225.0,8.100000,9985.0,NaN,2500.0,NaN,NaN
3,10156400020000,특수,구난,중형,KJW-HL112,2476.0,3.0,500.0,국제렉커차,2000,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,영업용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200009,200008.0,법인및사업자,0.0,274000.0,법인및사업자,NaN,103.0,13.600000,3105.0,NaN,3800.0,NaN,0.0
4,10156400030000,특수,구난,소형,KJW-HL113,2476.0,3.0,500.0,국제렉커차,2002,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,3280.0,1570.0,1410.0,수동,NaN,대구,자가용,단순이전,202001,당사자거래이전,일반소유용,NaN,일반소유용,NaN,200201,200112.0,개인,500000.0,151000.0,개인,50대 남자,103.0,13.600000,3415.0,NaN,3800.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512757,BFM20038600003320,화물,일반형-카고,대형,HS9.5T-MAN86,6871.0,2.0,6900.0,한성9.5톤카고,2020,경유,외산,ㄷ자형프레임캡오버형,11195.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ4LYXXXXXX,경북,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,202010,202010.0,개인,75500000.0,168000.0,법인및사업자,NaN,290.0,5.700000,18120.0,01650003300263018,2200.0,6x2,121800000.0
1512758,BXH20015200013318,화물,일반형-카고,대형,HJ8.5T-M6X2,6871.0,2.0,6000.0,한중8.5톤카고,2019,경유,외산,ㄷ자형프레임캡오버형,10660.0,2495.0,3220.0,6175.0,2065.0,1810.0,자동,WMAN18ZZ6KYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201907,201907.0,법인및사업자,0.0,345000.0,법인및사업자,NaN,290.0,5.700000,17070.0,01650003300013017,2200.0,6x2,117200000.0
1512759,C0120008200003320,화물,일반형-카고,대형,M6.5T-MANH-5775,6871.0,2.0,4200.0,메리트6.5톤트럭,2020,경유,외산,ㄷ자형프레임캡오버형,10045.0,2495.0,3220.0,5775.0,2065.0,1810.0,자동,WMAN18ZZ6LYXXXXXX,경북,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,202006,202005.0,법인및사업자,0.0,186000.0,법인및사업자,NaN,290.0,5.700000,14790.0,01650003300173018,2200.0,6x2,119800000.0
1512760,BXH20010200003317,화물,특수용도형-특수용도형,대형,HJ11M-MAN11.5,6871.0,2.0,11000.0,한중11톤냉장윙바디,2017,경유,외산,ㄷ자형프레임캡오버형,12905.0,2495.0,3920.0,6975.0,2070.0,1815.0,자동,WMAN18ZZ7HYXXXXXX,경기,영업용,단순이전,202207,당사자거래이전,일반소유용,NaN,일반소유용,NaN,201801,201711.0,개인,0.0,532000.0,개인,40대 여자,341.0,4.500000,24790.0,01620001700123317,2200.0,NaN,202000000.0
1512761,BFM20015000003317,화물,일반형-카고,대형,HS9.5T-MAN88,6871.0,2.0,7300.0,한성9.5톤만카고,2017,경유,외산,ㄷ자형프레임캡오버형,11320.0,2495.0,3220.0,6575.0,2065.0,1810.0,자동,WMAN18ZZ9HYXXXXXX,대전,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,201708,201708.0,법인및사업자,42000000.0,529000.0,법인및사업자,NaN,290.0,5.500000,18550.0,01620003300193316,2200.0,NaN,109900000.0

In [32]:
fillfunc('vehicle_cat','vin')

In [33]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                  29
engine                      196
displacement                978
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      27507
dom_import                    0
vehicle_body                935
len                           3
width                         3
height                        7
wheelbase                    21
front_wb                    792
back_wb                      30
transmission                 21
vin                        2816
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1048649
before_reg_detail             0
before_product_cat      1078730
first_reg_date                0
man_date                   5864
member_classi                 0
pur_amount                    2
mileage                   47582
before_member_classi          0
before_member_num        469754
max_output                43075
consum_rate                6457
weight                        1
first_manage_id          148165
rpm                       22374
dri_system              1302791
first_pur_amount          42189
dtype: int64

In [34]:
transfer[(transfer['vehicle_cat']).isna()]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,wheelbase,front_wb,back_wb,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
174416,10039000070001,화물,특수용도형-피견인,NaN,TD301ZA,0.0,0.0,24000.0,현정SUS코일복포트레일러,2000,NaN,국산,트레일러,9780.0,2460.0,3090.0,7930.0,0.0,1820.0,기타,KMZ1CR8APVUXXXXXX,울산,영업용,단순이전,202004,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199907,199712.0,개인,1000000.0,1000.0,법인및사업자,NaN,NaN,0.0,30500.0,NaN,NaN,NaN,NaN
189214,10051400000000,화물,특수용도형-피견인,NaN,SY-10-CT,0.0,0.0,10000.0,쌍용카트랜스포타트레일러,2000,NaN,국산,SEMI-TRAILER,12990.0,2495.0,3700.0,9690.0,0.0,1900.0,기타,KPAKR3C01SPXXXXXX,경기,영업용,단순이전,202004,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199603,NaN,법인및사업자,0.0,0.0,법인및사업자,NaN,NaN,0.0,17670.0,NaN,NaN,NaN,NaN
189887,10049000000000,화물,특수용도형-피견인,NaN,JCG-20XEE,0.0,0.0,20500.0,진도20피트구즈넥샤시,2000,NaN,국산,피견인형,8660.0,2480.0,1560.0,7450.0,0.0,1820.0,기타,KR1GDAHX2VBXXXXXX,인천,영업용,단순이전,202004,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199901,199712.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,24300.0,NaN,NaN,NaN,0.0
192026,10088700200000,화물,특수용도형-피견인,NaN,DL20LSLT0,0.0,0.0,24700.0,다임20kl액상소석회트레일러,2000,NaN,국산,피견인형,10590.0,2480.0,3200.0,8555.0,0.0,1820.0,기타,NaN,충남,자가용,단순이전,202005,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199812,199811.0,개인,0.0,1000.0,법인및사업자,NaN,NaN,0.0,30760.0,NaN,NaN,NaN,NaN
282808,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2000,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,영업용,단순이전,202006,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199703,199702.0,법인및사업자,0.0,1000.0,개인,40대 남자,NaN,0.0,30900.0,NaN,NaN,NaN,0.0
284826,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2000,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,자가용,단순이전,202006,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199703,199702.0,법인및사업자,2500000.0,1000.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,0.0
336253,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2000,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,자가용,단순이전,202007,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,199703,199702.0,법인및사업자,500000.0,1000.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,NaN
341104,20203200000000,화물,특수용도형-피견인,NaN,NEPTUNE 51,0.0,0.0,22900.0,베나루52M^3탱크트레일러,2000,NaN,외산,탱크트레일러,11900.0,2500.0,3980.0,7980.0,0.0,2095.0,기타,VFKKRD30CS2XXXXXX,울산,자가용,단순이전,202007,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,199603,199603.0,법인및사업자,2500000.0,1000.0,법인및사업자,NaN,NaN,0.0,28700.0,NaN,NaN,NaN,0.0
343166,10108000000000,화물,특수용도형-피견인,NaN,DL56BPVT0,0.0,0.0,25200.0,다임56M^3벌크트레일러,2000,NaN,국산,피견인형,12950.0,2480.0,3950.0,9300.0,0.0,2040.0,기타,NaN,충남,영업용,단순이전,202008,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199812,199802.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,30980.0,NaN,NaN,NaN,NaN
418065,10076600040000,화물,특수용도형-피견인,NaN,ICTT-29TC,0.0,0.0,26100.0,인정29KL중질유탱크트레일러,2000,NaN,국산,피견인형,11910.0,2460.0,3200.0,9870.0,0.0,1820.0,기타,KMV1CCDN0VHXXXXXX,울산,영업용,단순이전,202009,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199712,199712.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,31000.0,NaN,NaN,NaN,0.0
514245,10061500010000,화물,특수용도형-피견인,NaN,ICHT-40HE,0.0,0.0,370.0,인정수소운반트레일러,2000,NaN,국산,피견인형,12265.0,2440.0,3115.0,10775.0,0.0,1820.0,기타,KMV8AYDT0HVXXXXXX,전남,자가용,단순이전,202011,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199708,199707.0,법인및사업자,0.0,0.0,법인및사업자,NaN,NaN,0.0,30170.0,NaN,NaN,NaN,0.0
532669,10076400070000,화물,특수용도형-피견인,NaN,SHT-ALB24 EG,0.0,0.0,26600.0,신흥ALB24이지탱크트레일러,2001,NaN,국산,피견인형,9190.0,2490.0,3300.0,7073.0,0.0,1820.0,기타,NaN,울산,자가용,단순이전,202012,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199804,199803.0,법인및사업자,2700000.0,0.0,법인및사업자,NaN,NaN,0.0,30990.0,NaN,NaN,NaN,0.0
564890,10039000070001,화물,특수용도형-피견인,NaN,TD301ZA,0.0,0.0,24000.0,현정SUS코일복포트레일러,2001,NaN,국산,트레일러,9780.0,2460.0,3090.0,7930.0,0.0,1820.0,기타,KMZ1CR8APVUXXXXXX,부산,영업용,단순이전,202012,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199907,199712.0,개인,0.0,1000.0,개인,60대 남자,NaN,0.0,30500.0,NaN,NaN,NaN,NaN
564891,10039000070001,화물,특수용도형-피견인,NaN,TD301ZA,0.0,0.0,24000.0,현정SUS코일복포트레일러,2001,NaN,국산,트레일러,9780.0,2460.0,3090.0,7930.0,0.0,1820.0,기타,KMZ1CR8APVUXXXXXX,울산,영업용,단순이전,202012,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199907,199712.0,법인및사업자,0.0,1000.0,개인,40대 남자,NaN,0.0,30500.0,NaN,NaN,NaN,NaN
669559,10051400000000,화물,특수용도형-피견인,NaN,SY-10-CT,0.0,0.0,10000.0,쌍용카트랜스포타트레일러,2001,NaN,국산,SEMI-TRAILER,12990.0,2495.0,3700.0,9690.0,0.0,1900.0,기타,KPAKR3C01SPXXXXXX,경기,영업용,단순이전,202102,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199603,NaN,법인및사업자,0.0,0.0,법인및사업자,NaN,NaN,0.0,17670.0,NaN,NaN,NaN,NaN
726764,10049000000000,화물,특수용도형-피견인,NaN,JCG-20XEE,0.0,0.0,20500.0,진도20피트구즈넥샤시,2001,NaN,국산,피견인형,8660.0,2480.0,1560.0,7450.0,0.0,1820.0,기타,KR1GDAHX2VBXXXXXX,인천,영업용,단순이전,202103,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199901,199712.0,법인및사업자,1500000.0,1000.0,법인및사업자,NaN,NaN,0.0,24300.0,NaN,NaN,NaN,0.0
826520,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2001,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,자가용,단순이전,202105,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,199703,199702.0,개인,5000000.0,1000.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,0.0
829392,10051100000000,화물,특수용도형-피견인,NaN,DS-BCT-26001,0.0,0.0,26000.0,두성26M^32콘벌크트레일러,2001,NaN,국산,피견인형,9950.0,2480.0,3490.0,8520.0,0.0,1816.0,기타,KPSBGCFN6SSXXXXXX,충북,자가용,단순이전,202105,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,199511,199511.0,법인및사업자,500000.0,1000.0,법인및사업자,NaN,NaN,0.0,30980.0,NaN,NaN,NaN,0.0
917325,10084000000000,화물,특수용도형-피견인,NaN,TP050-CC1,0.0,0.0,8300.0,현정차량수송트레일러,2001,NaN,국산,세미트레일러,12535.0,2480.0,3420.0,10650.0,0.0,2180.0,기타,KMZ1CG8APVUXXXXXX,서울,영업용,단순이전,202107,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199705,199704.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,17030.0,NaN,NaN,NaN,NaN
984927,10023000000000,화물,특수용도형-피견인,NaN,ICBT-52A,0.0,0.0,23700.0,벌크트레일러,2001,NaN,국산,NaN,12320.0,2490.0,3910.0,10845.0,0.0,1860.0,기타,KMV2BA4T0PHXXXXXX,전남,영업용,단순이전,202109,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199306,NaN,개인,0.0,1000.0,법인및사업자,NaN,NaN,0.0,30480.0,NaN,NaN,NaN,NaN
1124156,10039000070001,화물,특수용도형-피견인,NaN,TD301ZA,0.0,0.0,24000.0,현정SUS코일복포트레일러,2001,NaN,국산,트레일러,9780.0,2460.0,3090.0,7930.0,0.0,1820.0,기타,KMZ1CR8APVUXXXXXX,경북,영업용,단순이전,202112,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199907,199712.0,개인,500000.0,1000.0,법인및사업자,NaN,NaN,0.0,30500.0,NaN,NaN,NaN,NaN
1134149,10023000000000,화물,특수용도형-피견인,NaN,ICBT-52A,0.0,0.0,23700.0,벌크트레일러,2001,NaN,국산,NaN,12320.0,2490.0,3910.0,10845.0,0.0,1860.0,기타,KMV2BA4T0PHXXXXXX,전남,영업용,단순이전,202112,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199306,NaN,개인,0.0,1000.0,법인및사업자,NaN,NaN,0.0,30480.0,NaN,NaN,NaN,NaN
1134150,10056400000000,화물,특수용도형-피견인,NaN,ICGC-40GA,0.0,0.0,27500.0,인정40피트구즈넥샤시,2001,NaN,국산,피견인형,12450.0,2445.0,1635.0,10430.0,0.0,1820.0,기타,KMV4CD3NOSHXXXXXX,경기,영업용,단순이전,202112,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199511,199511.0,법인및사업자,0.0,1000.0,법인및사업자,NaN,NaN,0.0,31000.0,NaN,NaN,NaN,0.0
1241943,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2002,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,자가용,단순이전,202202,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,199703,199702.0,법인및사업자,3500000.0,0.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,0.0
1243462,10035100010001,화물,특수용도형-피견인,NaN,ICTT-20C,0.0,0.0,23000.0,인정D.M.T.탱크트레일러,2002,NaN,국산,피견인형,10940.0,2450.0,3550.0,8905.0,0.0,1820.0,기타,KMV1JG4HOXHXXXXXX,울산,자가용,단순이전,202202,당사자거래이전,일반소유용,상품용,일반소유용,NaN,199906,199905.0,법인및사업자,2500000.0,0.0,법인및사업자,NaN,NaN,0.0,30750.0,NaN,NaN,NaN,0.0
1251290,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2002,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,자가용,단순이전,202202,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,199703,199702.0,법인및사업자,3500000.0,0.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,NaN
1390967,10050000000000,화물,특수용도형-피견인,NaN,DL285ATTO,0.0,0.0,25650.0,아스팔트탱크트레일러,2002,NaN,국산,탱크트레일러,12200.0,2480.0,3600.0,9944.0,0.0,1820.0,기타,NaN,경남,자가용,단순이전,202205,촉탁이전,매매상품용,상품용,일반소유용,NaN,199601,199601.0,개인,1700000.0,1000.0,개인,50대 남자,NaN,0.0,30850.0,NaN,NaN,NaN,0.0
1456965,10088700030000,화물,특수용도형-피견인,NaN,DL29DBTTO,0.0,0.0,26100.0,다임29KL보온탱크트레일러,2002,NaN,국산,피견인형,12280.0,2480.0,3240.0,9940.0,0.0,1820.0,기타,KN91NEZTZ8PXXXXXX,경북,영업용,단순이전,202206,당사자거래이전,일반소유용,NaN,일반소유용,NaN,199712,199712.0,법인및사업자,1300000.0,1000.0,법인및사업자,NaN,NaN,0.0,30950.0,NaN,NaN,NaN,NaN
1511640,10080900000000,화물,특수용도형-피견인,NaN,SMTR-BPT1-27M,0.0,0.0,24500.0,삼성27M^3PTA벌크트레일러,2002,NaN,국산,피견인형,10855.0,2498.0,3795.0,9390.0,0.0,0.0,기타,KNRBA5ANZVCXXXXXX,울산,영업용,단순이전,202207,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,199703,199702.0,법인및사업자,6500000.0,1000.0,법인및사업자,NaN,NaN,0.0,30900.0,NaN,NaN,NaN,NaN

In [35]:
transfer[(transfer['vehicle_name'].str.contains('트레일')) & (transfer['weight'] > 30000)]['vehicle_cat'].unique()

['대형', '소형', '중형', NaN, '경형']
Categories (4, object): ['경형', '대형', '소형', '중형']

In [36]:
transfer['product_cat'].unique()

[NaN, '상품용']
Categories (1, object): ['상품용']

In [37]:
fillfunc('vehicle_cat','vehicle_name')

In [38]:
transfer.dropna(subset='vehicle_cat', inplace = True)

In [39]:
transfer.isna().sum(0)

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      196
displacement                978
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      27484
dom_import                    0
vehicle_body                933
len                           3
width                         3
height                        7
wheelbase                    21
front_wb                    792
back_wb                      30
transmission                 21
vin                        2813
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1048631
before_reg_detail             0
before_product_cat      1078709
first_reg_date                0
man_date                   5860
member_classi                 0
pur_amount                    2
mileage                   47582
before_member_classi          0
before_member_num        469734
max_output                43052
consum_rate                6457
weight                        1
first_manage_id          148142
rpm                       22351
dri_system              1302768
first_pur_amount          42175
dtype: int64

In [40]:
transfer.loc[(transfer['displacement'] > 0) & (transfer['vehicle_name'].str.contains('DODGE'))
            & (transfer['fuel'].isna()), 'fuel'] = '휘발유'

In [41]:
transfer.drop(columns = ['front_wb','back_wb','wheelbase'], inplace = True)

In [42]:
transfer.reset_index(drop=True, inplace = True)

In [43]:
transfer.loc[transfer['first_reg_date']>202212]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
361892,A0810006208303109,화물,일반형-카고,소형,HRQJA-DX-A,2497.0,3.0,1000.0,포터Ⅱ(PORTERⅡ),2010,경유,국산,캡오버,5085.0,1740.0,1965.0,수동,KMFZCZ7JAAUXXXXXX,경기,자가용,단순이전,202008,매매업자거래이전,매매상품용,상품용,일반소유용,NaN,300906,200906.0,개인,1500000.0,272000.0,개인,60대 남자,126.0,11.4,2925.0,A0810006200003103,3800.0,NaN,11100000.0
361893,A0810006208303109,화물,일반형-카고,소형,HRQJA-DX-A,2497.0,3.0,1000.0,포터Ⅱ(PORTERⅡ),2010,경유,국산,캡오버,5085.0,1740.0,1965.0,수동,KMFZCZ7JAAUXXXXXX,경기,자가용,단순이전,202008,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,300906,200906.0,개인,1600000.0,272000.0,개인,40대 남자,126.0,11.4,2925.0,A0810006200003103,3800.0,NaN,11100000.0

In [44]:
transfer.loc[transfer['first_reg_date']>202212,'first_reg_date']= 200906

In [45]:
transfer.loc[transfer['first_reg_date'] == 1607,'first_reg_date'] = 201607

In [46]:
transfer.loc[transfer['first_reg_date'] == 212,'first_reg_date'] = 202201

In [47]:
transfer['sale_reg_date'] = transfer['sale_reg_date'].astype({'sale_reg_date':'object'})

for i, value in enumerate(transfer['sale_reg_date'].values):
    transfer['sale_reg_date'].values[i] = f"{str(value)[:4]}-{str(value)[4:]}-01"
    
transfer['first_reg_date'] = transfer['first_reg_date'].astype({'first_reg_date':'object'})

for i, value in enumerate(transfer['first_reg_date'].values):
    transfer['first_reg_date'].values[i] = f"{str(value)[:4]}-{str(value)[4:]}-01"    

file_12 = transfer
# 모델연도 datetime형태로 변경

file_12['sale_reg_date'] = pd.to_datetime(file_12['sale_reg_date'],format='%Y-%m-%d')

file_12['first_reg_date'] = pd.to_datetime(file_12['first_reg_date'],format='%Y-%m-%d')

transfer = file_12

In [48]:
transfer['man_date'].unique()

array([198008., 200006., 200102., 200008., 200112., 199411., 199004.,
       200205., 200301.,     nan, 200211., 199501., 200209., 199503.,
       200011., 200208., 199403., 199604., 199405., 199903., 199909.,
       200308., 200311., 200312., 200404., 200606., 200309., 200411.,
       200304., 200306., 200602., 200401., 200406., 200509., 200510.,
       200605., 200604., 200302., 200701., 200705., 200707., 200806.,
       200802., 200711., 200712., 200801., 200708., 200709., 200803.,
       200203., 200607., 200501., 200007., 199601., 199809., 199711.,
       199912., 200402., 200307., 200505., 200507., 199602., 200210.,
       200703., 200502., 200004., 200907., 200911., 201003., 200809.,
       201001., 200910., 201010., 201108., 201202., 201209., 201305.,
       201303., 201404., 201503., 201509., 201512., 201605., 201702.,
       201804., 201107., 201201., 201206., 201606., 201608., 200908.,
       201101., 201105., 201204., 201412., 201306., 201402., 201710.,
       201207., 201304., 201308., 201807., 201705., 201409., 201410.,
       201601., 200905., 201009., 201008., 201507., 200909., 201111.,
       201112., 201401., 201208., 201607., 201707., 200912., 201106.,
       201411., 201712., 201203., 200005., 200212., 199204., 200610.,
       201301., 201302., 200805., 200807., 201002., 201502., 201508.,
       201604., 201611., 201612., 200608., 200408., 200409., 201210.,
       200611., 200903., 201005., 201704., 201803., 201808., 201912.,
       201909., 201407., 199610., 200412., 201109., 201110., 201212.,
       200710., 200811., 200810., 201505., 201907., 201511., 201802.,
       201012., 199509., 200603., 200511., 201911., 201211., 200702.,
       201004., 201609., 201006., 201011., 201103., 201007., 201205.,
       201501., 201504., 201309., 201312., 200612., 200704., 201510.,
       201603., 201703., 199305., 201506., 201709., 201403., 201610.,
       201809., 201903., 201812., 200706., 201701., 201706., 201408.,
       200906., 201805., 201405., 201104., 200804., 201902., 201307.,
       201806., 201901., 201906., 200609., 200904., 201908., 201311.,
       201810., 201811., 199609., 199706., 199508., 199612., 201905.,
       201708., 201102., 201310., 201406., 201904., 201602., 201801.,
       201711., 200405., 200601., 200310., 200506., 199810., 200512.,
       200503., 200303., 200504., 201910., 199410., 199703., 199406.,
       199512., 199404., 199412., 199710., 200204., 200206., 199505.,
       200010., 199910., 200108., 199812., 200508., 200808., 200812.,
       200403., 200901., 200101., 200207., 200109., 200105., 200201.,
       200106., 200410., 200104., 200305., 200009., 200111., 199709.,
       197804., 200001., 199805., 199811., 200202., 199905., 199806.,
       199007., 199206., 199904., 200107., 199705., 199911., 200003.,
       200002., 199707., 199608., 198304., 199702., 199110., 199401.,
       199605., 199507., 200012., 199801., 199202., 199506., 200110.,
       197906., 199112., 198908., 199003., 199303., 199312., 202001.,
       200407., 200103., 199611., 199606., 199708., 199607., 199902.,
       200902., 199804., 199808., 199901., 198904., 199310., 199104.,
       198710., 199511., 199211., 199301., 199807., 199210., 199908.,
       199906., 199504., 198808., 199012., 199101., 199208., 199308.,
       199704., 199306., 199409., 199011., 199203., 199907., 199304.,
       199603., 199510., 199205., 199402., 199502., 199803., 199701.,
       199712., 198811., 198905., 199802., 199408., 199111., 198910.,
       199309., 199302., 198912., 199001., 199201., 199311., 198801.,
       198202., 198012., 199010., 202002., 198802., 199209., 196301.,
       198911., 199407., 199207., 199307., 199108., 198708., 199106.,
       198609., 198604., 199009., 199103., 198208., 198103., 199109.,
       198506., 199002., 198601., 198401., 202003., 198706., 198703.,
       199008., 198902., 199212., 199107., 198712., 199006., 199102.,
       198909., 198812., 198705., 202004., 198110., 197505., 198204.,
       198807., 198806., 198809., 198704., 198907., 198606., 197909.,
       198803., 199105., 202005., 194405., 198804., 198711., 198409.,
       202006., 198205., 197901., 197807., 197112., 198810., 198901.,
       198611., 198707., 198605., 202007., 196701., 196206., 198412.,
       202008., 202009., 198612., 196908., 197907., 198903., 198512.,
       198410., 198405., 198004., 202010., 198906., 198509., 198406.,
       202011., 198210., 202012., 198507., 197912., 197803., 197904.,
       197312., 202101., 202102., 198701., 198108., 202103., 198201.,
       197007., 198106., 198602., 197908., 197805., 196709., 196910.,
       202104.,   1011., 202105., 197412., 198502., 202106., 197808.,
       199005., 198610., 202107., 197408., 194206., 197502., 202108.,
       194512., 198010., 202109., 198109., 197404., 198104., 202110.,
       197902., 202111., 198510., 198003., 202112., 194412., 196912.,
       197707., 202201., 198001., 197203., 202202., 202203., 198112.,
       202204., 198501., 202205., 198603., 202206., 198007., 202207.,
        21008.], dtype=float32)

In [49]:
transfer.loc[transfer['man_date'] == 1011,'man_date'] = 201011

In [50]:
transfer.loc[transfer['man_date'] == 21008,'man_date'] = 201008

In [51]:
transfer.dropna(subset=['man_date'], inplace = True)

In [52]:
transfer['first_reg_date'] = pd.to_datetime(transfer['first_reg_date'],format='%Y-%m-%d')

In [53]:
transfer.reset_index(drop=True, inplace = True)

In [54]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      145
displacement                978
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26622
dom_import                    0
vehicle_body                567
len                           3
width                         3
height                        7
transmission                 21
vin                        2695
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043411
before_reg_detail             0
before_product_cat      1073303
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                   47571
before_member_classi          0
before_member_num        467033
max_output                41966
consum_rate                6250
weight                        1
first_manage_id          142282
rpm                       21301
dri_system              1296908
first_pur_amount          36495
dtype: int64

In [55]:
transfer.loc[(transfer['displacement'].isna()) & (transfer['vehicle_name'].str.contains('트레일')),'displacement'] = 0

In [56]:
transfer.loc[(transfer['displacement'].isna()) & (transfer['vehicle_name'].str.contains('샤시')),'displacement'] =0

In [57]:
transfer.loc[(transfer['displacement'].isna()) & (transfer['vehicle_name'].str.contains('트라마카고750')) ,'displacement'] = 0

In [58]:
transfer.loc[(transfer['displacement'].isna()) & (transfer['vehicle_name'].str.contains('BT500')) ,'displacement'] = 0

In [59]:
transfer.loc[(transfer['displacement'].isna()) & (transfer['vehicle_name'].str.contains('로우베드')) ,'displacement'] = 0

In [60]:
transfer.dropna(subset = 'displacement',inplace = True)

In [61]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      142
displacement                  0
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26619
dom_import                    0
vehicle_body                566
len                           3
width                         3
height                        7
transmission                 21
vin                        2692
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043408
before_reg_detail             0
before_product_cat      1073299
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                   47571
before_member_classi          0
before_member_num        467031
max_output                41962
consum_rate                6247
weight                        0
first_manage_id          142279
rpm                       21297
dri_system              1296904
first_pur_amount          36495
dtype: int64

In [62]:
transfer.reset_index(drop=True, inplace = True)

In [63]:
transfer[(transfer['displacement']>0) & (transfer['transmission'].isna())]

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
46920,0003412b000033115,화물,일반형-카고,소형,CT14Z,4300.0,2.0,500.0,시보레S10,2000,휘발유(무연),외산,2도어픽업,5040.0,1700.0,1630.0,NaN,1GCCT14Z1P0XXXXXX,서울,자가용,단순이전,2020-02-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2015-12-01,199312.0,개인,1000000.0,85000.0,개인,40대 남자,165.0,NaN,2180.0,NaN,5000.0,NaN,200000.0
432855,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,제주,자가용,단순이전,2020-10-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,개인,0.0,101000.0,개인,60대 남자,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0
530163,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,전북,자가용,단순이전,2020-12-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,개인,500000.0,106000.0,개인,40대 남자,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0
530169,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,전북,자가용,단순이전,2020-12-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,개인,400000.0,106000.0,개인,60대 여자,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0
627260,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,전북,자가용,단순이전,2021-02-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,법인및사업자,0.0,107000.0,개인,40대 남자,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0
780318,00034125000093315,화물,일반형-카고,소형,ZU77E,4009.0,5.0,400.0,포드스포츠트랙,2003,휘발유(무연),외산,본네트형,5260.0,1850.0,1760.0,NaN,1FMZU77E73UXXXXXX,부산,자가용,단순이전,2021-05-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2015-12-01,200312.0,개인,2000000.0,199000.0,개인,50대 남자,213.0,6.5,2745.0,NaN,5100.0,NaN,0.0
880796,00032828000013113,화물,일반형-카고,소형,C15903,4801.0,3.0,750.0,CHEVROLET SILVERADO,2003,휘발유(무연),외산,화물픽업형,5600.0,2000.0,1805.0,NaN,1GCEC14Z43ZXXXXXX,경기,자가용,단순이전,2021-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2013-06-01,200306.0,개인,1000000.0,171000.0,개인,40대 남자,170.0,NaN,2890.0,NaN,4500.0,NaN,1800000.0
990009,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,충남,자가용,단순이전,2021-09-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,개인,3000000.0,110000.0,법인및사업자,NaN,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0
1266149,00032828000013113,화물,일반형-카고,소형,C15903,4801.0,3.0,750.0,CHEVROLET SILVERADO,2003,휘발유(무연),외산,화물픽업형,5600.0,2000.0,1805.0,NaN,1GCEC14Z43ZXXXXXX,서울,자가용,단순이전,2022-03-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2013-06-01,200306.0,법인및사업자,29000000.0,180000.0,개인,30대 남자,170.0,NaN,2890.0,NaN,4500.0,NaN,1800000.0
1490045,00034625000023112,화물,일반형-카고,소형,SXT,3906.0,5.0,500.0,DAKOTA STX,2002,휘발유,외산,2도어본네트형,5464.0,1820.0,1730.0,NaN,1B7GG12X52SXXXXXX,경기,자가용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2012-07-01,200112.0,개인,0.0,114000.0,개인,40대 남자,175.0,9.7,2705.0,NaN,4800.0,NaN,800000.0

In [64]:
transfer[(transfer['vehicle_name'] == '시보레S10')]['transmission']

46920     NaN
530290     자동
Name: transmission, dtype: category
Categories (6, object): ['기타', '무단', '반자동', '변속기 없음', '수동', '자동']

In [65]:
transfer['transmission'].isna().sum()

21

In [66]:
fillfunc('transmission','vehicle_name')

In [67]:
transfer['transmission'].isna().sum()

13

In [68]:
transfer.dropna(subset='transmission',inplace = True)

In [69]:
transfer.reset_index(drop=True, inplace = True)

In [70]:
a = transfer[(transfer['mileage'] > 5000000)].index

In [71]:
transfer.drop(index = a, inplace = True)

In [72]:
dictmile = round((transfer[transfer['mileage']>50000]).groupby('vehicle_model')['mileage'].median()).to_dict()

In [73]:
for i in dictmile:
    print (i)

견인
구난
덤프
밴
일반형-카고
일반형-픽업
특수용도형
특수용도형-탱크로리
특수용도형-특수용도형
특수용도형-피견인
특수작업형

In [74]:
dictmile['견인']

640000.0

In [75]:
transfer['mileage'].isna().sum()

47571

In [76]:
for i in dictmile:
    transfer.loc[(transfer['vehicle_model'] == i) & (transfer['mileage'].isna()),'mileage'] = dictmile[i]

In [77]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      142
displacement                  0
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26616
dom_import                    0
vehicle_body                566
len                           3
width                         3
height                        7
transmission                  0
vin                        2691
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043268
before_reg_detail             0
before_product_cat      1073149
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                       0
before_member_classi          0
before_member_num        466943
max_output                41959
consum_rate                6242
weight                        0
first_manage_id          142236
rpm                       21294
dri_system              1296718
first_pur_amount          36484
dtype: int64

In [78]:
transfer.reset_index(drop=True, inplace = True)

In [79]:
a = transfer[(transfer['max_output'].isna()) & (transfer['displacement'] >0)].index

In [80]:
transfer.drop(index=a, inplace = True)

In [81]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      125
displacement                  0
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26616
dom_import                    0
vehicle_body                549
len                           0
width                         0
height                        1
transmission                  0
vin                        2689
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043244
before_reg_detail             0
before_product_cat      1073125
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                       0
before_member_classi          0
before_member_num        466926
max_output                41934
consum_rate                6230
weight                        0
first_manage_id          142220
rpm                       21278
dri_system              1296693
first_pur_amount          36483
dtype: int64

In [82]:
fillfunc('consum_rate','engine')

In [83]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                      125
displacement                  0
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26616
dom_import                    0
vehicle_body                549
len                           0
width                         0
height                        1
transmission                  0
vin                        2689
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043244
before_reg_detail             0
before_product_cat      1073125
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                       0
before_member_classi          0
before_member_num        466926
max_output                41934
consum_rate                4970
weight                        0
first_manage_id          142220
rpm                       21278
dri_system              1296693
first_pur_amount          36483
dtype: int64

In [84]:
fillfunc('consum_rate','manage_id')

In [85]:
transfer.reset_index(inplace=True, drop=True)

In [86]:
a = transfer[(transfer['consum_rate'].isna()) & (transfer['displacement'] > 0)].index

In [87]:
transfer.drop(index = a, inplace = True)

In [88]:
transfer[transfer['first_manage_id'].notna()].loc[:,['manage_id','first_manage_id']]

                 manage_id    first_manage_id
33       01520000300014303  01520000300004302
34       01520000300014303  01520000300004302
35       01520001500014304  01520003000004302
36       01520000500034303  01520000500004302
37       01520001500014304  01520003000004302
...                    ...                ...
1506651  BFM20038600003320  01650003300263018
1506652  BXH20015200013318  01650003300013017
1506653  C0120008200003320  01650003300173018
1506654  BXH20010200003317  01620001700123317
1506655  BFM20015000003317  01620003300193316

[1364435 rows x 2 columns]

In [89]:
transfer.isna().sum()

manage_id                     0
vehicle_type                  0
vehicle_model                 0
vehicle_cat                   0
engine                       98
displacement                  0
passenger                     0
max_load                      5
vehicle_name                  0
model_year                    0
fuel                      26616
dom_import                    0
vehicle_body                496
len                           0
width                         0
height                        1
transmission                  0
vin                        2660
reg_area                      0
purpose                       0
apply_category                0
sale_reg_date                 0
tranfer_reg_cat               0
reg_detail                    0
product_cat             1043124
before_reg_detail             0
before_product_cat      1073003
first_reg_date                0
man_date                      0
member_classi                 0
pur_amount                    2
mileage                       0
before_member_classi          0
before_member_num        466867
max_output                41934
consum_rate                4834
weight                        0
first_manage_id          142085
rpm                       21249
dri_system              1296558
first_pur_amount          36479
dtype: int64

In [90]:
transfer[transfer['first_pur_amount'].notna()].loc[:,['pur_amount','first_pur_amount']]

         pur_amount  first_pur_amount
1         2000000.0               0.0
3               0.0               0.0
4          500000.0               0.0
9         9000000.0               0.0
11        8000000.0               0.0
...             ...               ...
1506651  75500000.0       121800000.0
1506652         0.0       117200000.0
1506653         0.0       119800000.0
1506654         0.0       202000000.0
1506655  42000000.0       109900000.0

[1470041 rows x 2 columns]

In [91]:
transfer.reset_index(drop = True, inplace = True)

In [92]:
k = transfer[(transfer['rpm'].isna()) & (transfer['displacement'] > 0)].index

In [93]:
transfer.drop(index = k, inplace = True)

In [94]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506493 entries, 0 to 1506519
Data columns (total 41 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   manage_id             1506493 non-null  category
 1   vehicle_type          1506493 non-null  category
 2   vehicle_model         1506493 non-null  category
 3   vehicle_cat           1506493 non-null  category
 4   engine                1506403 non-null  category
 5   displacement          1506493 non-null  float32
 6   passenger             1506493 non-null  float32
 7   max_load              1506488 non-null  float32
 8   vehicle_name          1506493 non-null  category
 9   model_year            1506493 non-null  int32
 10  fuel                  1479877 non-null  category
 11  dom_import            1506493 non-null  category
 12  vehicle_body          1506015 non-null  category
 13  len                   1506493 non-null  float32
 14  width                 1506493 non-null  float32
 15  height                1506492 non-null  float32
 16  transmission          1506493 non-null  category
 17  vin                   1503845 non-null  category
 18  reg_area              1506493 non-null  category
 19  purpose               1506493 non-null  category
 20  apply_category        1506493 non-null  category
 21  sale_reg_date         1506493 non-null  datetime64[ns]
 22  tranfer_reg_cat       1506493 non-null  category
 23  reg_detail            1506493 non-null  category
 24  product_cat           463392 non-null   category
 25  before_reg_detail     1506493 non-null  category
 26  before_product_cat    433514 non-null   category
 27  first_reg_date        1506493 non-null  datetime64[ns]
 28  man_date              1506493 non-null  float32
 29  member_classi         1506493 non-null  category
 30  pur_amount            1506491 non-null  float32
 31  mileage               1506493 non-null  float32
 32  before_member_classi  1506493 non-null  category
 33  before_member_num     1039632 non-null  category
 34  max_output            1464559 non-null  float32
 35  consum_rate           1501659 non-null  float32
 36  weight                1506493 non-null  float32
 37  first_manage_id       1364435 non-null  category
 38  rpm                   1485271 non-null  float32
 39  dri_system            209962 non-null   category
 40  first_pur_amount      1470022 non-null  float32
dtypes: category(24), datetime64[ns](2), float32(14), int32(1)
memory usage: 170.6 MB

In [97]:
transfer

,manage_id,vehicle_type,vehicle_model,vehicle_cat,engine,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,vehicle_body,len,width,height,transmission,vin,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,dri_system,first_pur_amount
0,10007400060000,특수,구난,중형,KB940S-WR,10350.0,3.0,5000.0,기아마스타5톤렉카,2000,경유,국산,캡오바,8230.0,2465.0,2830.0,수동,NaN,울산,영업용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,1980-08-01,198008.0,개인,0.0,451000.0,개인,40대 여자,236.0,16.200001,11239.0,NaN,2200.0,NaN,NaN
1,10161000000000,특수,구난,중형,SW203,3907.0,3.0,1100.0,수성중형렉커트럭,2000,경유,국산,캡오버형,6395.0,2000.0,2690.0,수동,NaN,경북,자가용,단순이전,2020-01-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2000-07-01,200006.0,법인및사업자,2000000.0,301000.0,법인및사업자,NaN,155.0,10.000000,6025.0,NaN,3200.0,NaN,0.0
2,10149600030000,특수,구난,중형,SW500-1N,6606.0,3.0,1500.0,수성5톤슈퍼렉커트럭,2001,경유,국산,"ㄷ형프레임,캡오버형",7605.0,2195.0,3030.0,수동,NaN,제주,자가용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2001-03-01,200102.0,개인,0.0,198000.0,법인및사업자,NaN,225.0,8.100000,9985.0,NaN,2500.0,NaN,NaN
3,10156400020000,특수,구난,중형,KJW-HL112,2476.0,3.0,500.0,국제렉커차,2000,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,수동,NaN,대구,영업용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2000-09-01,200008.0,법인및사업자,0.0,274000.0,법인및사업자,NaN,103.0,13.600000,3105.0,NaN,3800.0,NaN,0.0
4,10156400030000,특수,구난,소형,KJW-HL113,2476.0,3.0,500.0,국제렉커차,2002,경유,국산,"H,세미본네트",5490.0,1820.0,2100.0,수동,NaN,대구,자가용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2002-01-01,200112.0,개인,500000.0,151000.0,개인,50대 남자,103.0,13.600000,3415.0,NaN,3800.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506515,BFM20038600003320,화물,일반형-카고,대형,HS9.5T-MAN86,6871.0,2.0,6900.0,한성9.5톤카고,2020,경유,외산,ㄷ자형프레임캡오버형,11195.0,2495.0,3220.0,자동,WMAN18ZZ4LYXXXXXX,경북,영업용,단순이전,2022-07-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2020-10-01,202010.0,개인,75500000.0,168000.0,법인및사업자,NaN,290.0,5.700000,18120.0,01650003300263018,2200.0,6x2,121800000.0
1506516,BXH20015200013318,화물,일반형-카고,대형,HJ8.5T-M6X2,6871.0,2.0,6000.0,한중8.5톤카고,2019,경유,외산,ㄷ자형프레임캡오버형,10660.0,2495.0,3220.0,자동,WMAN18ZZ6KYXXXXXX,경기,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2019-07-01,201907.0,법인및사업자,0.0,345000.0,법인및사업자,NaN,290.0,5.700000,17070.0,01650003300013017,2200.0,6x2,117200000.0
1506517,C0120008200003320,화물,일반형-카고,대형,M6.5T-MANH-5775,6871.0,2.0,4200.0,메리트6.5톤트럭,2020,경유,외산,ㄷ자형프레임캡오버형,10045.0,2495.0,3220.0,자동,WMAN18ZZ6LYXXXXXX,경북,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2020-06-01,202005.0,법인및사업자,0.0,186000.0,법인및사업자,NaN,290.0,5.700000,14790.0,01650003300173018,2200.0,6x2,119800000.0
1506518,BXH20010200003317,화물,특수용도형-특수용도형,대형,HJ11M-MAN11.5,6871.0,2.0,11000.0,한중11톤냉장윙바디,2017,경유,외산,ㄷ자형프레임캡오버형,12905.0,2495.0,3920.0,자동,WMAN18ZZ7HYXXXXXX,경기,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2018-01-01,201711.0,개인,0.0,532000.0,개인,40대 여자,341.0,4.500000,24790.0,01620001700123317,2200.0,NaN,202000000.0
1506519,BFM20015000003317,화물,일반형-카고,대형,HS9.5T-MAN88,6871.0,2.0,7300.0,한성9.5톤만카고,2017,경유,외산,ㄷ자형프레임캡오버형,11320.0,2495.0,3220.0,자동,WMAN18ZZ9HYXXXXXX,대전,영업용,단순이전,2022-07-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2017-08-01,201708.0,법인및사업자,42000000.0,529000.0,법인및사업자,NaN,290.0,5.500000,18550.0,01620003300193316,2200.0,NaN,109900000.0

In [99]:
cancel = transfer

cancel['mani_1'] = cancel['vin'].str[1:2].to_list()
conditionlist = [
    (cancel['mani_1'] == 'M'),
    (cancel['mani_1'] == 'N'),
    (cancel['mani_1'] == 'P'),
    (cancel['mani_1'] == 'L'),
    (cancel['mani_1'] == 'R'),
    (cancel['mani_1'] == 'V'),
(cancel['mani_1'] == 'B'),
(cancel['mani_1'] == 'A'),
(cancel['mani_1'] == 'D')]
choicelist = ['현대','기아','쌍용','대우','쌍용','폭스바겐','BMW','아우디','벤츠']
cancel['mani'] = np.select(conditionlist, choicelist, default = '기타')
transfer = cancel

In [100]:
cancel.loc[(cancel['dom_import'] == '외산') & (cancel['mani'] == '쌍용'), 'mani'] = '포르쉐'

In [101]:
cancel.drop(columns = 'mani_1', inplace = True)

In [102]:
transfer = cancel

In [111]:
transfer.drop(columns = ['engine','vehicle_body','vin','dri_system'], inplace = True)

In [113]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506493 entries, 0 to 1506519
Data columns (total 38 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   manage_id             1506493 non-null  category
 1   vehicle_type          1506493 non-null  category
 2   vehicle_model         1506493 non-null  category
 3   vehicle_cat           1506493 non-null  category
 4   displacement          1506493 non-null  float32
 5   passenger             1506493 non-null  float32
 6   max_load              1506488 non-null  float32
 7   vehicle_name          1506493 non-null  category
 8   model_year            1506493 non-null  int32
 9   fuel                  1479877 non-null  category
 10  dom_import            1506493 non-null  category
 11  len                   1506493 non-null  float32
 12  width                 1506493 non-null  float32
 13  height                1506492 non-null  float32
 14  transmission          1506493 non-null  category
 15  reg_area              1506493 non-null  category
 16  purpose               1506493 non-null  category
 17  apply_category        1506493 non-null  category
 18  sale_reg_date         1506493 non-null  datetime64[ns]
 19  tranfer_reg_cat       1506493 non-null  category
 20  reg_detail            1506493 non-null  category
 21  product_cat           463392 non-null   category
 22  before_reg_detail     1506493 non-null  category
 23  before_product_cat    433514 non-null   category
 24  first_reg_date        1506493 non-null  datetime64[ns]
 25  man_date              1506493 non-null  float32
 26  member_classi         1506493 non-null  category
 27  pur_amount            1506491 non-null  float32
 28  mileage               1506493 non-null  float32
 29  before_member_classi  1506493 non-null  category
 30  before_member_num     1039632 non-null  category
 31  max_output            1464559 non-null  float32
 32  consum_rate           1501659 non-null  float32
 33  weight                1506493 non-null  float32
 34  first_manage_id       1364435 non-null  category
 35  rpm                   1485271 non-null  float32
 36  first_pur_amount      1470022 non-null  float32
 37  mani                  1506493 non-null  object
dtypes: category(20), datetime64[ns](2), float32(14), int32(1), object(1)
memory usage: 170.1+ MB

In [115]:
def going_to_light(df):
    for i in df.columns:
        if df[i].dtype == 'int64':
            df[i] = df[i].astype('int32')
        if df[i].dtype == 'float64':
            df[i] = df[i].astype('float32')
        if df[i].dtype == 'object':
            df[i] = df[i].astype('category')
    return df

In [116]:
going_to_light(transfer)

,manage_id,vehicle_type,vehicle_model,vehicle_cat,displacement,passenger,max_load,vehicle_name,model_year,fuel,dom_import,len,width,height,transmission,reg_area,purpose,apply_category,sale_reg_date,tranfer_reg_cat,reg_detail,product_cat,before_reg_detail,before_product_cat,first_reg_date,man_date,member_classi,pur_amount,mileage,before_member_classi,before_member_num,max_output,consum_rate,weight,first_manage_id,rpm,first_pur_amount,mani
0,10007400060000,특수,구난,중형,10350.0,3.0,5000.0,기아마스타5톤렉카,2000,경유,국산,8230.0,2465.0,2830.0,수동,울산,영업용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,1980-08-01,198008.0,개인,0.0,451000.0,개인,40대 여자,236.0,16.200001,11239.0,NaN,2200.0,NaN,기타
1,10161000000000,특수,구난,중형,3907.0,3.0,1100.0,수성중형렉커트럭,2000,경유,국산,6395.0,2000.0,2690.0,수동,경북,자가용,단순이전,2020-01-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2000-07-01,200006.0,법인및사업자,2000000.0,301000.0,법인및사업자,NaN,155.0,10.000000,6025.0,NaN,3200.0,0.0,기타
2,10149600030000,특수,구난,중형,6606.0,3.0,1500.0,수성5톤슈퍼렉커트럭,2001,경유,국산,7605.0,2195.0,3030.0,수동,제주,자가용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2001-03-01,200102.0,개인,0.0,198000.0,법인및사업자,NaN,225.0,8.100000,9985.0,NaN,2500.0,NaN,기타
3,10156400020000,특수,구난,중형,2476.0,3.0,500.0,국제렉커차,2000,경유,국산,5490.0,1820.0,2100.0,수동,대구,영업용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2000-09-01,200008.0,법인및사업자,0.0,274000.0,법인및사업자,NaN,103.0,13.600000,3105.0,NaN,3800.0,0.0,기타
4,10156400030000,특수,구난,소형,2476.0,3.0,500.0,국제렉커차,2002,경유,국산,5490.0,1820.0,2100.0,수동,대구,자가용,단순이전,2020-01-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2002-01-01,200112.0,개인,500000.0,151000.0,개인,50대 남자,103.0,13.600000,3415.0,NaN,3800.0,0.0,기타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506515,BFM20038600003320,화물,일반형-카고,대형,6871.0,2.0,6900.0,한성9.5톤카고,2020,경유,외산,11195.0,2495.0,3220.0,자동,경북,영업용,단순이전,2022-07-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2020-10-01,202010.0,개인,75500000.0,168000.0,법인및사업자,NaN,290.0,5.700000,18120.0,01650003300263018,2200.0,121800000.0,현대
1506516,BXH20015200013318,화물,일반형-카고,대형,6871.0,2.0,6000.0,한중8.5톤카고,2019,경유,외산,10660.0,2495.0,3220.0,자동,경기,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2019-07-01,201907.0,법인및사업자,0.0,345000.0,법인및사업자,NaN,290.0,5.700000,17070.0,01650003300013017,2200.0,117200000.0,현대
1506517,C0120008200003320,화물,일반형-카고,대형,6871.0,2.0,4200.0,메리트6.5톤트럭,2020,경유,외산,10045.0,2495.0,3220.0,자동,경북,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2020-06-01,202005.0,법인및사업자,0.0,186000.0,법인및사업자,NaN,290.0,5.700000,14790.0,01650003300173018,2200.0,119800000.0,현대
1506518,BXH20010200003317,화물,특수용도형-특수용도형,대형,6871.0,2.0,11000.0,한중11톤냉장윙바디,2017,경유,외산,12905.0,2495.0,3920.0,자동,경기,영업용,단순이전,2022-07-01,당사자거래이전,일반소유용,NaN,일반소유용,NaN,2018-01-01,201711.0,개인,0.0,532000.0,개인,40대 여자,341.0,4.500000,24790.0,01620001700123317,2200.0,202000000.0,현대
1506519,BFM20015000003317,화물,일반형-카고,대형,6871.0,2.0,7300.0,한성9.5톤만카고,2017,경유,외산,11320.0,2495.0,3220.0,자동,대전,영업용,단순이전,2022-07-01,매매업자거래이전,일반소유용,NaN,매매상품용,상품용,2017-08-01,201708.0,법인및사업자,42000000.0,529000.0,법인및사업자,NaN,290.0,5.500000,18550.0,01620003300193316,2200.0,109900000.0,현대

In [117]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506493 entries, 0 to 1506519
Data columns (total 38 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   manage_id             1506493 non-null  category
 1   vehicle_type          1506493 non-null  category
 2   vehicle_model         1506493 non-null  category
 3   vehicle_cat           1506493 non-null  category
 4   displacement          1506493 non-null  float32
 5   passenger             1506493 non-null  float32
 6   max_load              1506488 non-null  float32
 7   vehicle_name          1506493 non-null  category
 8   model_year            1506493 non-null  int32
 9   fuel                  1479877 non-null  category
 10  dom_import            1506493 non-null  category
 11  len                   1506493 non-null  float32
 12  width                 1506493 non-null  float32
 13  height                1506492 non-null  float32
 14  transmission          1506493 non-null  category
 15  reg_area              1506493 non-null  category
 16  purpose               1506493 non-null  category
 17  apply_category        1506493 non-null  category
 18  sale_reg_date         1506493 non-null  datetime64[ns]
 19  tranfer_reg_cat       1506493 non-null  category
 20  reg_detail            1506493 non-null  category
 21  product_cat           463392 non-null   category
 22  before_reg_detail     1506493 non-null  category
 23  before_product_cat    433514 non-null   category
 24  first_reg_date        1506493 non-null  datetime64[ns]
 25  man_date              1506493 non-null  float32
 26  member_classi         1506493 non-null  category
 27  pur_amount            1506491 non-null  float32
 28  mileage               1506493 non-null  float32
 29  before_member_classi  1506493 non-null  category
 30  before_member_num     1039632 non-null  category
 31  max_output            1464559 non-null  float32
 32  consum_rate           1501659 non-null  float32
 33  weight                1506493 non-null  float32
 34  first_manage_id       1364435 non-null  category
 35  rpm                   1485271 non-null  float32
 36  first_pur_amount      1470022 non-null  float32
 37  mani                  1506493 non-null  category
dtypes: category(21), datetime64[ns](2), float32(14), int32(1)
memory usage: 160.1 MB

In [118]:
transfer.to_parquet('transfer_final.parquet', index = False)